import {
  MAJ3_FORMULA_META,
  MIN3_FORMULA_META,
  DIM3_FORMULA_META,
  AUG3_FORMULA_META,
  MAJ3_FLAT5_FORMULA_META,
} from './FAMILIES/CHORD3_FORMULA_META'

import {
  MAJ3_ADD6_FORMULA_META,
  MIN3_ADD6_FORMULA_META,
  MAJ3_ADD6_ADD9_FORMULA_META,
  MIN3_ADD6_ADD9_FORMULA_META,
  MAJ3_ADD9_FORMULA_META,
  MAJ3_ADD11_FORMULA_META,
  MIN3_ADD9_FORMULA_META,
  MIN3_ADD11_FORMULA_META,
} from './FAMILIES/CHORD3_EX_FORMULA_META'

import {
  MAJ7_FORMULA_META,
  DOM7_FORMULA_META,
  MIN7_FORMULA_META,
  HALFDIM7_FORMULA_META,
  DIM7_FORMULA_META,
  MIN_MAJ7_FORMULA_META,
} from './FAMILIES/CHORD7_FORMULA_META'

import {
  MAJ7_ADD11_FORMULA_META,
  DOM7_ADD6_FORMULA_META,
} from './FAMILIES/CHORD7_ADD_FORMULA_META'

import {
  MAJ9_FORMULA_META,
  DOM9_FORMULA_META,
  MIN9_FORMULA_META,
  MIN_MAJ9_FORMULA_META,
} from './FAMILIES/CHORD9_FORMULA_META'

import {
  MAJ11_FORMULA_META,
  DOM11_FORMULA_META,
  MIN11_FORMULA_META,
  MIN_MAJ11_FORMULA_META,
} from './FAMILIES/CHORD11_FORMULA_META'

import {
  MAJ13_FORMULA_META,
  DOM13_FORMULA_META,
  MIN13_FORMULA_META,
  MIN_MAJ13_FORMULA_META,
} from './FAMILIES/CHORD13_FORMULA_META'

import {
  SUS2_FORMULA_META,
  SUS4_FORMULA_META,
  DOM7_SUS2_FORMULA_META,
  DOM7_SUS4_FORMULA_META,
  DOM7_SUS4_FLAT9_FORMULA_META,
  MAJ7_SUS2_FORMULA_META,
  MAJ7_SUS4_FORMULA_META,
  DOM9_SUS4_FORMULA_META,
  MAJ9_SUS4_FORMULA_META,
  DOM13_SUS4_FORMULA_META,
  MAJ13_SUS4_FORMULA_META,
  MAJ13_SUS2_FORMULA_META,
} from './FAMILIES/CHORD_SUS_FORMULA_META'

import {
  DOM7_SHARP5_FORMULA_META,
  DOM7_FLAT5_FORMULA_META,
  DOM7_FLAT9_FORMULA_META,
  DOM7_SHARP9_FORMULA_META,
  DOM7_SHARP11_FORMULA_META,
  DOM7_FLAT13_FORMULA_META,
  DOM7_FLAT5_FLAT9_FORMULA_META,
  DOM7_FLAT5_SHARP9_FORMULA_META,
  DOM7_SHARP5_FLAT9_FORMULA_META,
  DOM7_SHARP5_SHARP9_FORMULA_META,
} from './FAMILIES/DOM7_ALTER_FORMULA_META'

import {
  MAJ7_FLAT5_FORMULA_META,
  MAJ7_FLAT9_FORMULA_META,
  MAJ7_FLAT13_FORMULA_META,
  MAJ7_SHARP11_FORMULA_META,
  AUG7_FORMULA_META,
} from './FAMILIES/MAJ7_ALTER_FORMULA_META'

import {
  MIN7_SHARP5_FORMULA_META,
  MIN_MAJ7_FLAT5_FORMULA_META,
  MIN_MAJ7_SHARP5_FORMULA_META,
} from './FAMILIES/MIN7_ALTER_FORMULA_META'

import {
  DOM9_SHARP5_FORMULA_META,
  DOM9_SHARP11_FORMULA_META,
  DOM9_FLAT13_FORMULA_META,
  DOM9_ADD13_FORMULA_META,
} from './FAMILIES/DOM9_ALTER_FORMULA_META'

import {
  MAJ9_FLAT5_FORMULA_META,
  MAJ9_SHARP5_FORMULA_META,
  MAJ9_SHARP11_FORMULA_META,
  MAJ9_FLAT13_FORMULA_META,
} from './FAMILIES/MAJ9_ALTER_FORMULA_META'

import {
  MIN9_FLAT5_FORMULA_META,
} from './FAMILIES/MIN9_ALTER_FORMULA_META'

import {
  DOM11_FLAT5_FORMULA_META,
  DOM11_SHARP5_FORMULA_META,
  DOM11_FLAT9_FORMULA_META,
  DOM11_SHARP9_FORMULA_META,
  DOM11_FLAT13_FORMULA_META,
} from './FAMILIES/DOM11_ALTER_FORMULA_META'

import {
  MIN11_FLAT5_FORMULA_META,
} from './FAMILIES/MIN11_ALTER_FORMULA_META'

import {
  DOM13_FLAT5_FORMULA_META,
  DOM13_SHARP5_FORMULA_META,
  DOM13_FLAT9_FORMULA_META,
  DOM13_SHARP9_FORMULA_META,
  DOM13_SHARP11_FORMULA_META,
} from './FAMILIES/DOM13_ALTER_FORMULA_META'

import {
  MAJ13_FLAT5_FORMULA_META,
  MAJ13_SHARP5_FORMULA_META,
  MAJ13_FLAT9_FORMULA_META,
  MAJ13_SHARP11_FORMULA_META,
} from './FAMILIES/MAJ13_ALTER_FORMULA_META'

import type { I_ChordFormulaMeta } from './types'

/**
 * 和弦公式元数据映射表
 * 将和弦公式 ID 映射到对应的元数据对象
 */
export const CHORD_FORMULA_META_MAP: Record<string, I_ChordFormulaMeta> = {
  // ========== 三和弦 ==========
  maj3: MAJ3_FORMULA_META,
  min3: MIN3_FORMULA_META,
  dim3: DIM3_FORMULA_META,
  aug3: AUG3_FORMULA_META,
  maj3b5: MAJ3_FLAT5_FORMULA_META,

  // ========== 三和弦扩展 ==========
  maj3add6: MAJ3_ADD6_FORMULA_META,
  min3add6: MIN3_ADD6_FORMULA_META,
  maj3add6add9: MAJ3_ADD6_ADD9_FORMULA_META,
  min3add6add9: MIN3_ADD6_ADD9_FORMULA_META,
  maj3add9: MAJ3_ADD9_FORMULA_META,
  maj3add11: MAJ3_ADD11_FORMULA_META,
  min3add9: MIN3_ADD9_FORMULA_META,
  min3add11: MIN3_ADD11_FORMULA_META,

  // ========== 基础七和弦 ==========
  maj7: MAJ7_FORMULA_META,
  dom7: DOM7_FORMULA_META,
  min7: MIN7_FORMULA_META,
  halfdim7: HALFDIM7_FORMULA_META,
  dim7: DIM7_FORMULA_META,
  minmaj7: MIN_MAJ7_FORMULA_META,

  // ========== 七和弦add扩展 ==========
  maj7add11: MAJ7_ADD11_FORMULA_META,
  dom7add6: DOM7_ADD6_FORMULA_META,

  // ========== 挂留和弦 ==========
  sus2: SUS2_FORMULA_META,
  sus4: SUS4_FORMULA_META,
  dom7sus2: DOM7_SUS2_FORMULA_META,
  dom7sus4: DOM7_SUS4_FORMULA_META,
  dom7sus4b9: DOM7_SUS4_FLAT9_FORMULA_META,
  maj7sus2: MAJ7_SUS2_FORMULA_META,
  maj7sus4: MAJ7_SUS4_FORMULA_META,
  dom9sus4: DOM9_SUS4_FORMULA_META,
  maj9sus4: MAJ9_SUS4_FORMULA_META,
  dom13sus4: DOM13_SUS4_FORMULA_META,
  maj13sus4: MAJ13_SUS4_FORMULA_META,
  maj13sus2: MAJ13_SUS2_FORMULA_META,

  // ========== 基础九和弦 ==========
  maj9: MAJ9_FORMULA_META,
  dom9: DOM9_FORMULA_META,
  min9: MIN9_FORMULA_META,
  minmaj9: MIN_MAJ9_FORMULA_META,

  // ========== 属九变音 ==========
  "dom9#5": DOM9_SHARP5_FORMULA_META,
  "dom9#11": DOM9_SHARP11_FORMULA_META,
  "dom9b13": DOM9_FLAT13_FORMULA_META,
  "dom9add13": DOM9_ADD13_FORMULA_META,

  // ========== 大九变音 ==========
  "maj9b5": MAJ9_FLAT5_FORMULA_META,
  "maj9#5": MAJ9_SHARP5_FORMULA_META,
  "maj9#11": MAJ9_SHARP11_FORMULA_META,
  "maj9b13": MAJ9_FLAT13_FORMULA_META,

  // ========== 小九变音 ==========
  "min9b5": MIN9_FLAT5_FORMULA_META,

  // ========== 基础十一和弦 ==========
  maj11: MAJ11_FORMULA_META,
  dom11: DOM11_FORMULA_META,
  min11: MIN11_FORMULA_META,
  minmaj11: MIN_MAJ11_FORMULA_META,

  // ========== 属十一变音 ==========
  "dom11b5": DOM11_FLAT5_FORMULA_META,
  "dom11#5": DOM11_SHARP5_FORMULA_META,
  "dom11b9": DOM11_FLAT9_FORMULA_META,
  "dom11#9": DOM11_SHARP9_FORMULA_META,
  "dom11b13": DOM11_FLAT13_FORMULA_META,

  // ========== 小十一变音 ==========
  "min11b5": MIN11_FLAT5_FORMULA_META,

  // ========== 基础十三和弦 ==========
  maj13: MAJ13_FORMULA_META,
  dom13: DOM13_FORMULA_META,
  min13: MIN13_FORMULA_META,
  minmaj13: MIN_MAJ13_FORMULA_META,

  // ========== 属十三变音 ==========
  "dom13b5": DOM13_FLAT5_FORMULA_META,
  "dom13#5": DOM13_SHARP5_FORMULA_META,
  "dom13b9": DOM13_FLAT9_FORMULA_META,
  "dom13#9": DOM13_SHARP9_FORMULA_META,
  "dom13#11": DOM13_SHARP11_FORMULA_META,

  // ========== 大十三变音 ==========
  "maj13b5": MAJ13_FLAT5_FORMULA_META,
  "maj13#5": MAJ13_SHARP5_FORMULA_META,
  "maj13b9": MAJ13_FLAT9_FORMULA_META,
  "maj13#11": MAJ13_SHARP11_FORMULA_META,

  // ========== 属七变音 ==========
  "dom7#5": DOM7_SHARP5_FORMULA_META,
  "dom7b5": DOM7_FLAT5_FORMULA_META,
  "dom7b9": DOM7_FLAT9_FORMULA_META,
  "dom7#9": DOM7_SHARP9_FORMULA_META,
  "dom7#11": DOM7_SHARP11_FORMULA_META,
  "dom7b13": DOM7_FLAT13_FORMULA_META,
  "dom7b5b9": DOM7_FLAT5_FLAT9_FORMULA_META,
  "dom7b5#9": DOM7_FLAT5_SHARP9_FORMULA_META,
  "dom7#5b9": DOM7_SHARP5_FLAT9_FORMULA_META,
  "dom7#5#9": DOM7_SHARP5_SHARP9_FORMULA_META,

  // ========== 大七变音 ==========
  "maj7b5": MAJ7_FLAT5_FORMULA_META,
  "maj7b9": MAJ7_FLAT9_FORMULA_META,
  "maj7b13": MAJ7_FLAT13_FORMULA_META,
  "maj7#11": MAJ7_SHARP11_FORMULA_META,
  augmaj7: AUG7_FORMULA_META,

  // ========== 小七变音 ==========
  "min7#5": MIN7_SHARP5_FORMULA_META,
  "minmaj7b5": MIN_MAJ7_FLAT5_FORMULA_META,
  "minmaj7#5": MIN_MAJ7_SHARP5_FORMULA_META,
}

