// ========== 和弦公式 ID 定义 ==========
export { default as CHORD_FORMULA_ID } from './CHORD_FORMULA_ID'

// ========== 类型定义 ==========
export type { I_ChordFormulaMeta } from './types'

// ========== 三和弦族 ==========
export { MAJ3_FORMULA_META } from './FAMILIES/CHORD3_FORMULA_META'
export { MIN3_FORMULA_META } from './FAMILIES/CHORD3_FORMULA_META'
export { DIM3_FORMULA_META } from './FAMILIES/CHORD3_FORMULA_META'
export { AUG3_FORMULA_META } from './FAMILIES/CHORD3_FORMULA_META'
export { MAJ3_FLAT5_FORMULA_META } from './FAMILIES/CHORD3_FORMULA_META'

// ========== 三和弦扩展族 ==========
export { MAJ3_ADD6_FORMULA_META } from './FAMILIES/CHORD3_EX_FORMULA_META'
export { MIN3_ADD6_FORMULA_META } from './FAMILIES/CHORD3_EX_FORMULA_META'
export { MAJ3_ADD6_ADD9_FORMULA_META } from './FAMILIES/CHORD3_EX_FORMULA_META'
export { MIN3_ADD6_ADD9_FORMULA_META } from './FAMILIES/CHORD3_EX_FORMULA_META'
export { MAJ3_ADD9_FORMULA_META } from './FAMILIES/CHORD3_EX_FORMULA_META'
export { MAJ3_ADD11_FORMULA_META } from './FAMILIES/CHORD3_EX_FORMULA_META'
export { MIN3_ADD9_FORMULA_META } from './FAMILIES/CHORD3_EX_FORMULA_META'
export { MIN3_ADD11_FORMULA_META } from './FAMILIES/CHORD3_EX_FORMULA_META'

// ========== 基础七和弦族 ==========
export { MAJ7_FORMULA_META } from './FAMILIES/CHORD7_FORMULA_META'
export { DOM7_FORMULA_META } from './FAMILIES/CHORD7_FORMULA_META'
export { MIN7_FORMULA_META } from './FAMILIES/CHORD7_FORMULA_META'
export { HALFDIM7_FORMULA_META } from './FAMILIES/CHORD7_FORMULA_META'
export { DIM7_FORMULA_META } from './FAMILIES/CHORD7_FORMULA_META'
export { MIN_MAJ7_FORMULA_META } from './FAMILIES/CHORD7_FORMULA_META'

// ========== 属七变音族 ==========
export { DOM7_SHARP5_FORMULA_META } from './FAMILIES/DOM7_ALTER_FORMULA_META'
export { DOM7_FLAT5_FORMULA_META } from './FAMILIES/DOM7_ALTER_FORMULA_META'
export { DOM7_FLAT9_FORMULA_META } from './FAMILIES/DOM7_ALTER_FORMULA_META'
export { DOM7_SHARP9_FORMULA_META } from './FAMILIES/DOM7_ALTER_FORMULA_META'
export { DOM7_SHARP11_FORMULA_META } from './FAMILIES/DOM7_ALTER_FORMULA_META'
export { DOM7_FLAT13_FORMULA_META } from './FAMILIES/DOM7_ALTER_FORMULA_META'
export { DOM7_FLAT5_FLAT9_FORMULA_META } from './FAMILIES/DOM7_ALTER_FORMULA_META'
export { DOM7_FLAT5_SHARP9_FORMULA_META } from './FAMILIES/DOM7_ALTER_FORMULA_META'
export { DOM7_SHARP5_FLAT9_FORMULA_META } from './FAMILIES/DOM7_ALTER_FORMULA_META'
export { DOM7_SHARP5_SHARP9_FORMULA_META } from './FAMILIES/DOM7_ALTER_FORMULA_META'

// ========== 大七变音族 ==========
export { MAJ7_FLAT5_FORMULA_META } from './FAMILIES/MAJ7_ALTER_FORMULA_META'
export { MAJ7_FLAT9_FORMULA_META } from './FAMILIES/MAJ7_ALTER_FORMULA_META'
export { MAJ7_FLAT13_FORMULA_META } from './FAMILIES/MAJ7_ALTER_FORMULA_META'
export { MAJ7_SHARP11_FORMULA_META } from './FAMILIES/MAJ7_ALTER_FORMULA_META'
export { AUG7_FORMULA_META } from './FAMILIES/MAJ7_ALTER_FORMULA_META'

// ========== 小七变音族 ==========
export { MIN7_SHARP5_FORMULA_META } from './FAMILIES/MIN7_ALTER_FORMULA_META'
export { MIN_MAJ7_FLAT5_FORMULA_META } from './FAMILIES/MIN7_ALTER_FORMULA_META'
export { MIN_MAJ7_SHARP5_FORMULA_META } from './FAMILIES/MIN7_ALTER_FORMULA_META'

// ========== 七和弦add扩展族 ==========
export { MAJ7_ADD11_FORMULA_META } from './FAMILIES/CHORD7_ADD_FORMULA_META'
export { DOM7_ADD6_FORMULA_META } from './FAMILIES/CHORD7_ADD_FORMULA_META'

// ========== 挂留和弦族 ==========
export { SUS2_FORMULA_META } from './FAMILIES/CHORD_SUS_FORMULA_META'
export { SUS4_FORMULA_META } from './FAMILIES/CHORD_SUS_FORMULA_META'
export { DOM7_SUS2_FORMULA_META } from './FAMILIES/CHORD_SUS_FORMULA_META'
export { DOM7_SUS4_FORMULA_META } from './FAMILIES/CHORD_SUS_FORMULA_META'
export { DOM7_SUS4_FLAT9_FORMULA_META } from './FAMILIES/CHORD_SUS_FORMULA_META'
export { MAJ7_SUS2_FORMULA_META } from './FAMILIES/CHORD_SUS_FORMULA_META'
export { MAJ7_SUS4_FORMULA_META } from './FAMILIES/CHORD_SUS_FORMULA_META'
export { DOM9_SUS4_FORMULA_META } from './FAMILIES/CHORD_SUS_FORMULA_META'
export { MAJ9_SUS4_FORMULA_META } from './FAMILIES/CHORD_SUS_FORMULA_META'
export { DOM13_SUS4_FORMULA_META } from './FAMILIES/CHORD_SUS_FORMULA_META'
export { MAJ13_SUS4_FORMULA_META } from './FAMILIES/CHORD_SUS_FORMULA_META'
export { MAJ13_SUS2_FORMULA_META } from './FAMILIES/CHORD_SUS_FORMULA_META'

// ========== 基础九和弦族 ==========
export { MAJ9_FORMULA_META } from './FAMILIES/CHORD9_FORMULA_META'
export { DOM9_FORMULA_META } from './FAMILIES/CHORD9_FORMULA_META'
export { MIN9_FORMULA_META } from './FAMILIES/CHORD9_FORMULA_META'
export { MIN_MAJ9_FORMULA_META } from './FAMILIES/CHORD9_FORMULA_META'

// ========== 属九变音族 ==========
export { DOM9_SHARP5_FORMULA_META } from './FAMILIES/DOM9_ALTER_FORMULA_META'
export { DOM9_SHARP11_FORMULA_META } from './FAMILIES/DOM9_ALTER_FORMULA_META'
export { DOM9_FLAT13_FORMULA_META } from './FAMILIES/DOM9_ALTER_FORMULA_META'
export { DOM9_ADD13_FORMULA_META } from './FAMILIES/DOM9_ALTER_FORMULA_META'

// ========== 大九变音族 ==========
export { MAJ9_FLAT5_FORMULA_META } from './FAMILIES/MAJ9_ALTER_FORMULA_META'
export { MAJ9_SHARP5_FORMULA_META } from './FAMILIES/MAJ9_ALTER_FORMULA_META'
export { MAJ9_SHARP11_FORMULA_META } from './FAMILIES/MAJ9_ALTER_FORMULA_META'
export { MAJ9_FLAT13_FORMULA_META } from './FAMILIES/MAJ9_ALTER_FORMULA_META'

// ========== 小九变音族 ==========
export { MIN9_FLAT5_FORMULA_META } from './FAMILIES/MIN9_ALTER_FORMULA_META'

// ========== 基础十一和弦族 ==========
export { MAJ11_FORMULA_META } from './FAMILIES/CHORD11_FORMULA_META'
export { DOM11_FORMULA_META } from './FAMILIES/CHORD11_FORMULA_META'
export { MIN11_FORMULA_META } from './FAMILIES/CHORD11_FORMULA_META'
export { MIN_MAJ11_FORMULA_META } from './FAMILIES/CHORD11_FORMULA_META'

// ========== 属十一变音族 ==========
export { DOM11_FLAT5_FORMULA_META } from './FAMILIES/DOM11_ALTER_FORMULA_META'
export { DOM11_SHARP5_FORMULA_META } from './FAMILIES/DOM11_ALTER_FORMULA_META'
export { DOM11_FLAT9_FORMULA_META } from './FAMILIES/DOM11_ALTER_FORMULA_META'
export { DOM11_SHARP9_FORMULA_META } from './FAMILIES/DOM11_ALTER_FORMULA_META'
export { DOM11_FLAT13_FORMULA_META } from './FAMILIES/DOM11_ALTER_FORMULA_META'

// ========== 小十一变音族 ==========
export { MIN11_FLAT5_FORMULA_META } from './FAMILIES/MIN11_ALTER_FORMULA_META'

// ========== 基础十三和弦族 ==========
export { MAJ13_FORMULA_META } from './FAMILIES/CHORD13_FORMULA_META'
export { DOM13_FORMULA_META } from './FAMILIES/CHORD13_FORMULA_META'
export { MIN13_FORMULA_META } from './FAMILIES/CHORD13_FORMULA_META'
export { MIN_MAJ13_FORMULA_META } from './FAMILIES/CHORD13_FORMULA_META'

// ========== 属十三变音族 ==========
export { DOM13_FLAT5_FORMULA_META } from './FAMILIES/DOM13_ALTER_FORMULA_META'
export { DOM13_SHARP5_FORMULA_META } from './FAMILIES/DOM13_ALTER_FORMULA_META'
export { DOM13_FLAT9_FORMULA_META } from './FAMILIES/DOM13_ALTER_FORMULA_META'
export { DOM13_SHARP9_FORMULA_META } from './FAMILIES/DOM13_ALTER_FORMULA_META'
export { DOM13_SHARP11_FORMULA_META } from './FAMILIES/DOM13_ALTER_FORMULA_META'

// ========== 大十三变音族 ==========
export { MAJ13_FLAT5_FORMULA_META } from './FAMILIES/MAJ13_ALTER_FORMULA_META'
export { MAJ13_SHARP5_FORMULA_META } from './FAMILIES/MAJ13_ALTER_FORMULA_META'
export { MAJ13_FLAT9_FORMULA_META } from './FAMILIES/MAJ13_ALTER_FORMULA_META'
export { MAJ13_SHARP11_FORMULA_META } from './FAMILIES/MAJ13_ALTER_FORMULA_META'
