import { isNil } from 'es-toolkit'
import NATURAL_MAJOR_SCALE_META from "../SCALE_INSTANCE_META/DIATONIC_MODE_META/NATURAL_MAJOR_SCALE_META"
import DORIAN_SCALE_META from "../SCALE_INSTANCE_META/DIATONIC_MODE_META/DORIAN_SCALE_META"
import PHRYGIAN_SCALE_META from "../SCALE_INSTANCE_META/DIATONIC_MODE_META/PHRYGIAN_SCALE_META"
import LYDIAN_SCALE_META from "../SCALE_INSTANCE_META/DIATONIC_MODE_META/LYDIAN_SCALE_META"
import MIXOLYDIAN_SCALE_META from "../SCALE_INSTANCE_META/DIATONIC_MODE_META/MIXOLYDIAN_SCALE_META"
import NATURAL_MINOR_SCALE_META from "../SCALE_INSTANCE_META/DIATONIC_MODE_META/NATURAL_MINOR_SCALE_META"
import LOCRIAN_SCALE_META from "../SCALE_INSTANCE_META/DIATONIC_MODE_META/LOCRIAN_SCALE_META"
import HARMONIC_MAJOR_SCALE_META from "../SCALE_INSTANCE_META/HARMONIC_MAJOR_MODE_META/HARMONIC_MAJOR_SCALE_META"
import MELODIC_MAJOR_DESCENDING_SCALE_META from "../SCALE_INSTANCE_META/MELODIC_MAJOR_MODE_META/MELODIC_MAJOR_DESCENDING_SCALE_META"
import HARMONIC_MINOR_SCALE_META from "../SCALE_INSTANCE_META/HARMONIC_MINOR_MODE_META/HARMONIC_MINOR_SCALE_META"
import LOCRIAN_SHARP6_SCALE_META from "../SCALE_INSTANCE_META/HARMONIC_MINOR_MODE_META/LOCRIAN_SHARP6_SCALE_META"
import IONIAN_SHARP5_SCALE_META from "../SCALE_INSTANCE_META/HARMONIC_MINOR_MODE_META/IONIAN_SHARP5_SCALE_META"
import DORIAN_SHARP4_SCALE_META from "../SCALE_INSTANCE_META/HARMONIC_MINOR_MODE_META/DORIAN_SHARP4_SCALE_META"
import PHRYGIAN_DOMINANT_SCALE_META from "../SCALE_INSTANCE_META/HARMONIC_MINOR_MODE_META/PHRYGIAN_DOMINANT_SCALE_META"
import LYDIAN_SHARP2_SCALE_META from "../SCALE_INSTANCE_META/HARMONIC_MINOR_MODE_META/LYDIAN_SHARP2_SCALE_META"
import MELODIC_MINOR_ASCENDING_SCALE_META from "../SCALE_INSTANCE_META/MELODIC_MINOR_MODE_META/MELODIC_MINOR_ASCENDING_SCALE_META"
import DORIAN_FLAT2_SCALE_META from "../SCALE_INSTANCE_META/MELODIC_MINOR_MODE_META/DORIAN_FLAT2_SCALE_META"
import LYDIAN_AUGMENTED_SCALE_META from "../SCALE_INSTANCE_META/MELODIC_MINOR_MODE_META/LYDIAN_AUGMENTED_SCALE_META"
import LYDIAN_DOMINANT_SCALE_META from "../SCALE_INSTANCE_META/MELODIC_MINOR_MODE_META/LYDIAN_DOMINANT_SCALE_META"
import LOCRIAN_SHARP2_SCALE_META from "../SCALE_INSTANCE_META/MELODIC_MINOR_MODE_META/LOCRIAN_SHARP2_SCALE_META"
import DOUBLE_HARMONIC_MAJOR_SCALE_META from "../SCALE_INSTANCE_META/DOUBLE_HARMONIC_MODE_META/DOUBLE_HARMONIC_MAJOR_SCALE_META"
import HUNGARIAN_MINOR_SCALE_META from "../SCALE_INSTANCE_META/DOUBLE_HARMONIC_MODE_META/HUNGARIAN_MINOR_SCALE_META"
import ORIENTAL_SCALE_META from "../SCALE_INSTANCE_META/DOUBLE_HARMONIC_MODE_META/ORIENTAL_SCALE_META"
import IONIAN_SHARP2_SHARP5_SCALE_META from "../SCALE_INSTANCE_META/DOUBLE_HARMONIC_MODE_META/IONIAN_SHARP2_SHARP5_SCALE_META"
import GONG_SCALE_META from "../SCALE_INSTANCE_META/CHINESE_PENTATONIC_MODE_META/GONG_SCALE_META"
import SHANG_SCALE_META from "../SCALE_INSTANCE_META/CHINESE_PENTATONIC_MODE_META/SHANG_SCALE_META"
import JUE_SCALE_META from "../SCALE_INSTANCE_META/CHINESE_PENTATONIC_MODE_META/JUE_SCALE_META"
import ZHI_SCALE_META from "../SCALE_INSTANCE_META/CHINESE_PENTATONIC_MODE_META/ZHI_SCALE_META"
import YU_SCALE_META from "../SCALE_INSTANCE_META/CHINESE_PENTATONIC_MODE_META/YU_SCALE_META"
import YA_YUE_GONG_SCALE_META from "../SCALE_INSTANCE_META/CHINESE_YAYUE_MODE_META/YA_YUE_GONG_SCALE_META"
import YA_YUE_SHANG_SCALE_META from "../SCALE_INSTANCE_META/CHINESE_YAYUE_MODE_META/YA_YUE_SHANG_SCALE_META"
import YA_YUE_JUE_SCALE_META from "../SCALE_INSTANCE_META/CHINESE_YAYUE_MODE_META/YA_YUE_JUE_SCALE_META"
import YA_YUE_ZHI_SCALE_META from "../SCALE_INSTANCE_META/CHINESE_YAYUE_MODE_META/YA_YUE_ZHI_SCALE_META"
import YA_YUE_YU_SCALE_META from "../SCALE_INSTANCE_META/CHINESE_YAYUE_MODE_META/YA_YUE_YU_SCALE_META"
import QING_YUE_GONG_SCALE_META from "../SCALE_INSTANCE_META/CHINESE_QINGYUE_MODE_META/QING_YUE_GONG_SCALE_META"
import QING_YUE_SHANG_SCALE_META from "../SCALE_INSTANCE_META/CHINESE_QINGYUE_MODE_META/QING_YUE_SHANG_SCALE_META"
import QING_YUE_JUE_SCALE_META from "../SCALE_INSTANCE_META/CHINESE_QINGYUE_MODE_META/QING_YUE_JUE_SCALE_META"
import QING_YUE_ZHI_SCALE_META from "../SCALE_INSTANCE_META/CHINESE_QINGYUE_MODE_META/QING_YUE_ZHI_SCALE_META"
import QING_YUE_YU_SCALE_META from "../SCALE_INSTANCE_META/CHINESE_QINGYUE_MODE_META/QING_YUE_YU_SCALE_META"
import YAN_YUE_GONG_SCALE_META from "../SCALE_INSTANCE_META/CHINESE_YANYUE_MODE_META/YAN_YUE_GONG_SCALE_META"
import YAN_YUE_SHANG_SCALE_META from "../SCALE_INSTANCE_META/CHINESE_YANYUE_MODE_META/YAN_YUE_SHANG_SCALE_META"
import YAN_YUE_JUE_SCALE_META from "../SCALE_INSTANCE_META/CHINESE_YANYUE_MODE_META/YAN_YUE_JUE_SCALE_META"
import YAN_YUE_ZHI_SCALE_META from "../SCALE_INSTANCE_META/CHINESE_YANYUE_MODE_META/YAN_YUE_ZHI_SCALE_META"
import YAN_YUE_YU_SCALE_META from "../SCALE_INSTANCE_META/CHINESE_YANYUE_MODE_META/YAN_YUE_YU_SCALE_META"

const SCALE_META_MAP: Record<string, any[]> = {
	// DIATONIC
	NATURAL_MAJOR: NATURAL_MAJOR_SCALE_META,
	DORIAN: DORIAN_SCALE_META,
	PHRYGIAN: PHRYGIAN_SCALE_META,
	LYDIAN: LYDIAN_SCALE_META,
	MIXOLYDIAN: MIXOLYDIAN_SCALE_META,
	NATURAL_MINOR: NATURAL_MINOR_SCALE_META,
	LOCRIAN: LOCRIAN_SCALE_META,
	// HARMONIC_MAJOR
	HARMONIC_MAJOR: HARMONIC_MAJOR_SCALE_META,
	// MELODIC_MAJOR
	MELODIC_MAJOR_DESCENDING: MELODIC_MAJOR_DESCENDING_SCALE_META,
	// HARMONIC_MINOR
	HARMONIC_MINOR: HARMONIC_MINOR_SCALE_META,
	LOCRIAN_SHARP6: LOCRIAN_SHARP6_SCALE_META,
	IONIAN_SHARP5: IONIAN_SHARP5_SCALE_META,
	DORIAN_SHARP4: DORIAN_SHARP4_SCALE_META,
	PHRYGIAN_DOMINANT: PHRYGIAN_DOMINANT_SCALE_META,
	LYDIAN_SHARP2: LYDIAN_SHARP2_SCALE_META,
	// MELODIC_MINOR
	MELODIC_MINOR_ASCENDING: MELODIC_MINOR_ASCENDING_SCALE_META,
	DORIAN_FLAT2: DORIAN_FLAT2_SCALE_META,
	LYDIAN_AUGMENTED: LYDIAN_AUGMENTED_SCALE_META,
	LYDIAN_DOMINANT: LYDIAN_DOMINANT_SCALE_META,
	LOCRIAN_SHARP2: LOCRIAN_SHARP2_SCALE_META,
	// DOUBLE_HARMONIC
	DOUBLE_HARMONIC_MAJOR: DOUBLE_HARMONIC_MAJOR_SCALE_META,
	HUNGARIAN_MINOR: HUNGARIAN_MINOR_SCALE_META,
	ORIENTAL: ORIENTAL_SCALE_META,
	IONIAN_SHARP2_SHARP5: IONIAN_SHARP2_SHARP5_SCALE_META,
	// CHINESE_PENTATONIC
	GONG: GONG_SCALE_META,
	SHANG: SHANG_SCALE_META,
	JUE: JUE_SCALE_META,
	ZHI: ZHI_SCALE_META,
	YU: YU_SCALE_META,
	// CHINESE_YAYUE
	YA_YUE_GONG: YA_YUE_GONG_SCALE_META,
	YA_YUE_SHANG: YA_YUE_SHANG_SCALE_META,
	YA_YUE_JUE: YA_YUE_JUE_SCALE_META,
	YA_YUE_ZHI: YA_YUE_ZHI_SCALE_META,
	YA_YUE_YU: YA_YUE_YU_SCALE_META,
	// CHINESE_QINGYUE
	QING_YUE_GONG: QING_YUE_GONG_SCALE_META,
	QING_YUE_SHANG: QING_YUE_SHANG_SCALE_META,
	QING_YUE_JUE: QING_YUE_JUE_SCALE_META,
	QING_YUE_ZHI: QING_YUE_ZHI_SCALE_META,
	QING_YUE_YU: QING_YUE_YU_SCALE_META,
	// CHINESE_YANYUE
	YAN_YUE_GONG: YAN_YUE_GONG_SCALE_META,
	YAN_YUE_SHANG: YAN_YUE_SHANG_SCALE_META,
	YAN_YUE_JUE: YAN_YUE_JUE_SCALE_META,
	YAN_YUE_ZHI: YAN_YUE_ZHI_SCALE_META,
	YAN_YUE_YU: YAN_YUE_YU_SCALE_META,
}

export const getScaleModeMetaById = (scaleModeId: string) => {
	const meta = SCALE_META_MAP[scaleModeId]
	if (isNil(meta)) {
		throw new Error(`Scale mode not found: ${scaleModeId}`)
	}
	return meta
}
