import collect from 'collect.js'
import {
  SUS2_FORMULA_META,
  SUS4_FORMULA_META,
  DOM7_SUS2_FORMULA_META,
  DOM7_SUS4_FORMULA_META,
  DOM7_SUS4_FLAT9_FORMULA_META,
  MAJ7_SUS2_FORMULA_META,
  MAJ7_SUS4_FORMULA_META,
  DOM9_SUS4_FORMULA_META,
  MAJ9_SUS4_FORMULA_META,
  DOM13_SUS4_FORMULA_META,
  MAJ13_SUS4_FORMULA_META,
  MAJ13_SUS2_FORMULA_META,
} from '../../static/FAMILIES/CHORD_SUS_FORMULA_META.ts'
import type { I_ChordFormulaMeta } from '../../static/types.ts'

/**
 * 获取挂留和弦族的元数据列表
 */
export const getChordSusList = () => {
  return collect<I_ChordFormulaMeta>([
    SUS2_FORMULA_META,
    SUS4_FORMULA_META,
    DOM7_SUS2_FORMULA_META,
    DOM7_SUS4_FORMULA_META,
    DOM7_SUS4_FLAT9_FORMULA_META,
    MAJ7_SUS2_FORMULA_META,
    MAJ7_SUS4_FORMULA_META,
    DOM9_SUS4_FORMULA_META,
    MAJ9_SUS4_FORMULA_META,
    DOM13_SUS4_FORMULA_META,
    MAJ13_SUS4_FORMULA_META,
    MAJ13_SUS2_FORMULA_META,
  ])
}
