import collect from 'collect.js'
import {
  DOM7_SHARP5_FORMULA_META,
  DOM7_FLAT5_FORMULA_META,
  DOM7_FLAT9_FORMULA_META,
  DOM7_SHARP9_FORMULA_META,
  DOM7_SHARP11_FORMULA_META,
  DOM7_FLAT13_FORMULA_META,
  DOM7_FLAT5_FLAT9_FORMULA_META,
  DOM7_FLAT5_SHARP9_FORMULA_META,
  DOM7_SHARP5_FLAT9_FORMULA_META,
  DOM7_SHARP5_SHARP9_FORMULA_META,
} from '../../static/FAMILIES/DOM7_ALTER_FORMULA_META'
import type { I_ChordFormulaMeta } from '../../static/types'

/**
 * 获取属七变音族的元数据列表
 */
export const getDom7AlterList = () => {
  return collect<I_ChordFormulaMeta>([
    DOM7_SHARP5_FORMULA_META,
    DOM7_FLAT5_FORMULA_META,
    DOM7_FLAT9_FORMULA_META,
    DOM7_SHARP9_FORMULA_META,
    DOM7_SHARP11_FORMULA_META,
    DOM7_FLAT13_FORMULA_META,
    DOM7_FLAT5_FLAT9_FORMULA_META,
    DOM7_FLAT5_SHARP9_FORMULA_META,
    DOM7_SHARP5_FLAT9_FORMULA_META,
    DOM7_SHARP5_SHARP9_FORMULA_META,
  ])
}
