// 类型导出
export type { I_ScaleModeMeta } from "./types"

// 自然大调族（教会调式）
export {
  NATURAL_MAJOR_MODE_META,
  DORIAN_MODE_META,
  PHRYGIAN_MODE_META,
  LYDIAN_MODE_META,
  MIXOLYDIAN_MODE_META,
  NATURAL_MINOR_MODE_META,
  LOCRIAN_MODE_META,
} from "./FAMILIES/DIATONIC_MODE_META"

// 和声大调族
export { HARMONIC_MAJOR_MODE_META } from "./FAMILIES/HARMONIC_MAJOR_MODE_META"

// 旋律大调族
export { MELODIC_MAJOR_DESCENDING_MODE_META } from "./FAMILIES/MELODIC_MAJOR_MODE_META"

// 和声小调族
export {
  HARMONIC_MINOR_MODE_META,
  LOCRIAN_SHARP6_MODE_META,
  IONIAN_SHARP5_MODE_META,
  DORIAN_SHARP4_MODE_META,
  PHRYGIAN_DOMINANT_MODE_META,
  LYDIAN_SHARP2_MODE_META,
} from "./FAMILIES/HARMONIC_MINOR_MODE_META"

// 旋律小调族
export {
  MELODIC_MINOR_ASCENDING_MODE_META,
  DORIAN_FLAT2_MODE_META,
  LYDIAN_AUGMENTED_MODE_META,
  LYDIAN_DOMINANT_MODE_META,
  LOCRIAN_SHARP2_MODE_META,
} from "./FAMILIES/MELODIC_MINOR_MODE_META"

// 双重和声大调族
export {
  DOUBLE_HARMONIC_MAJOR_MODE_META,
  HUNGARIAN_MINOR_MODE_META,
  ORIENTAL_MODE_META,
  IONIAN_SHARP2_SHARP5_MODE_META,
} from "./FAMILIES/DOUBLE_HARMONIC_MODE_META"

// 中国五声调式
export {
  GONG_MODE_META,
  SHANG_MODE_META,
  JUE_MODE_META,
  ZHI_MODE_META,
  YU_MODE_META,
} from "./FAMILIES/CHINESE_PENTATONIC_MODE_META"

// 中国雅乐七声调式
export {
  YA_YUE_GONG_MODE_META,
  YA_YUE_SHANG_MODE_META,
  YA_YUE_JUE_MODE_META,
  YA_YUE_ZHI_MODE_META,
  YA_YUE_YU_MODE_META,
} from "./FAMILIES/CHINESE_YAYUE_MODE_META"

// 中国清乐七声调式
export {
  QING_YUE_GONG_MODE_META,
  QING_YUE_SHANG_MODE_META,
  QING_YUE_JUE_MODE_META,
  QING_YUE_ZHI_MODE_META,
  QING_YUE_YU_MODE_META,
} from "./FAMILIES/CHINESE_QINGYUE_MODE_META"

// 中国燕乐七声调式
export {
  YAN_YUE_GONG_MODE_META,
  YAN_YUE_SHANG_MODE_META,
  YAN_YUE_JUE_MODE_META,
  YAN_YUE_ZHI_MODE_META,
  YAN_YUE_YU_MODE_META,
} from "./FAMILIES/CHINESE_YANYUE_MODE_META"
