import {
  NATURAL_MAJOR_MODE_META,
  LYDIAN_MODE_META,
  MIXOLYDIAN_MODE_META,
  NATURAL_MINOR_MODE_META,
  DORIAN_MODE_META,
  PHRYGIAN_MODE_META,
  LOCRIAN_MODE_META,
} from './FAMILIES/DIATONIC_MODE_META'

import {
  HARMONIC_MAJOR_MODE_META,
} from './FAMILIES/HARMONIC_MAJOR_MODE_META'

import {
  HARMONIC_MINOR_MODE_META,
  PHRYGIAN_DOMINANT_MODE_META,
  LOCRIAN_SHARP6_MODE_META,
  IONIAN_SHARP5_MODE_META,
  DORIAN_SHARP4_MODE_META,
  LYDIAN_SHARP2_MODE_META,
} from './FAMILIES/HARMONIC_MINOR_MODE_META'

import {
  MELODIC_MAJOR_DESCENDING_MODE_META,
} from './FAMILIES/MELODIC_MAJOR_MODE_META'

import {
  MELODIC_MINOR_ASCENDING_MODE_META,
  LYDIAN_DOMINANT_MODE_META,
  DORIAN_FLAT2_MODE_META,
  LYDIAN_AUGMENTED_MODE_META,
  LOCRIAN_SHARP2_MODE_META,
} from './FAMILIES/MELODIC_MINOR_MODE_META'

import {
  DOUBLE_HARMONIC_MAJOR_MODE_META,
  HUNGARIAN_MINOR_MODE_META,
  ORIENTAL_MODE_META,
  IONIAN_SHARP2_SHARP5_MODE_META,
} from './FAMILIES/DOUBLE_HARMONIC_MODE_META'

import {
  GONG_MODE_META,
  SHANG_MODE_META,
  JUE_MODE_META,
  ZHI_MODE_META,
  YU_MODE_META,
} from './FAMILIES/CHINESE_PENTATONIC_MODE_META'

import {
  YA_YUE_GONG_MODE_META,
  YA_YUE_SHANG_MODE_META,
  YA_YUE_JUE_MODE_META,
  YA_YUE_ZHI_MODE_META,
  YA_YUE_YU_MODE_META,
} from './FAMILIES/CHINESE_YAYUE_MODE_META'

import {
  QING_YUE_GONG_MODE_META,
  QING_YUE_SHANG_MODE_META,
  QING_YUE_JUE_MODE_META,
  QING_YUE_ZHI_MODE_META,
  QING_YUE_YU_MODE_META,
} from './FAMILIES/CHINESE_QINGYUE_MODE_META'

import {
  YAN_YUE_GONG_MODE_META,
  YAN_YUE_SHANG_MODE_META,
  YAN_YUE_JUE_MODE_META,
  YAN_YUE_ZHI_MODE_META,
  YAN_YUE_YU_MODE_META,
} from './FAMILIES/CHINESE_YANYUE_MODE_META'

import type { I_ScaleModeMeta } from './types'

/**
 * 调式元数据映射表
 * 将调式 ID 映射到对应的元数据对象
 */
export const SCALE_MODE_META_MAP: Record<string, I_ScaleModeMeta> = {
  // ========== 自然大调族（教会调式） ==========
  NATURAL_MAJOR: NATURAL_MAJOR_MODE_META,
  IONIAN: NATURAL_MAJOR_MODE_META,
  LYDIAN: LYDIAN_MODE_META,
  MIXOLYDIAN: MIXOLYDIAN_MODE_META,

  // ========== 自然小调族 ==========
  NATURAL_MINOR: NATURAL_MINOR_MODE_META,
  AEOLIAN: NATURAL_MINOR_MODE_META,
  DORIAN: DORIAN_MODE_META,
  PHRYGIAN: PHRYGIAN_MODE_META,
  LOCRIAN: LOCRIAN_MODE_META,

  // ========== 和声大调族 ==========
  HARMONIC_MAJOR: HARMONIC_MAJOR_MODE_META,

  // ========== 和声小调族 ==========
  HARMONIC_MINOR: HARMONIC_MINOR_MODE_META,
  PHRYGIAN_DOMINANT: PHRYGIAN_DOMINANT_MODE_META,
  LOCRIAN_SHARP6: LOCRIAN_SHARP6_MODE_META,
  IONIAN_SHARP5: IONIAN_SHARP5_MODE_META,
  DORIAN_SHARP4: DORIAN_SHARP4_MODE_META,
  LYDIAN_SHARP2: LYDIAN_SHARP2_MODE_META,

  // ========== 旋律大调族 ==========
  MELODIC_MAJOR_DESCENDING: MELODIC_MAJOR_DESCENDING_MODE_META,

  // ========== 旋律小调族 ==========
  MELODIC_MINOR_ASCENDING: MELODIC_MINOR_ASCENDING_MODE_META,
  LYDIAN_DOMINANT: LYDIAN_DOMINANT_MODE_META,
  DORIAN_FLAT2: DORIAN_FLAT2_MODE_META,
  LYDIAN_AUGMENTED: LYDIAN_AUGMENTED_MODE_META,
  LOCRIAN_SHARP2: LOCRIAN_SHARP2_MODE_META,

  // ========== 双重和声大调族 ==========
  DOUBLE_HARMONIC_MAJOR: DOUBLE_HARMONIC_MAJOR_MODE_META,
  HUNGARIAN_MINOR: HUNGARIAN_MINOR_MODE_META,
  ORIENTAL: ORIENTAL_MODE_META,
  IONIAN_SHARP2_SHARP5: IONIAN_SHARP2_SHARP5_MODE_META,

  // ========== 中国五声调式 ==========
  GONG: GONG_MODE_META,
  SHANG: SHANG_MODE_META,
  JUE: JUE_MODE_META,
  ZHI: ZHI_MODE_META,
  YU: YU_MODE_META,

  // ========== 中国雅乐七声调式 ==========
  YA_YUE_GONG: YA_YUE_GONG_MODE_META,
  YA_YUE_SHANG: YA_YUE_SHANG_MODE_META,
  YA_YUE_JUE: YA_YUE_JUE_MODE_META,
  YA_YUE_ZHI: YA_YUE_ZHI_MODE_META,
  YA_YUE_YU: YA_YUE_YU_MODE_META,

  // ========== 中国清乐七声调式 ==========
  QING_YUE_GONG: QING_YUE_GONG_MODE_META,
  QING_YUE_SHANG: QING_YUE_SHANG_MODE_META,
  QING_YUE_JUE: QING_YUE_JUE_MODE_META,
  QING_YUE_ZHI: QING_YUE_ZHI_MODE_META,
  QING_YUE_YU: QING_YUE_YU_MODE_META,

  // ========== 中国燕乐七声调式 ==========
  YAN_YUE_GONG: YAN_YUE_GONG_MODE_META,
  YAN_YUE_SHANG: YAN_YUE_SHANG_MODE_META,
  YAN_YUE_JUE: YAN_YUE_JUE_MODE_META,
  YAN_YUE_ZHI: YAN_YUE_ZHI_MODE_META,
  YAN_YUE_YU: YAN_YUE_YU_MODE_META,
}
