/**
 * 所有和弦实例元数据聚合
 *
 * 从 CHORD_INSTANCE_META 目录下所有子模块导入和弦实例数据，
 * 提供统一的访问入口。
 */

import { I_ChordInstanceMeta } from "./types";
import AUG3_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_META/AUG3_CHORD_META";
import DIM3_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_META/DIM3_CHORD_META";
import MAJ3_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_META/MAJ3_CHORD_META";
import MAJ3_FLAT5_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_META/MAJ3_FLAT5_CHORD_META";
import MIN3_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_META/MIN3_CHORD_META";
import MAJ3ADD11_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_EX_META/MAJ3ADD11_CHORD_META";
import MAJ3ADD6ADD9_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_EX_META/MAJ3ADD6ADD9_CHORD_META";
import MAJ3ADD6_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_EX_META/MAJ3ADD6_CHORD_META";
import MAJ3ADD9_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_EX_META/MAJ3ADD9_CHORD_META";
import MIN3ADD11_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_EX_META/MIN3ADD11_CHORD_META";
import MIN3ADD6ADD9_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_EX_META/MIN3ADD6ADD9_CHORD_META";
import MIN3ADD6_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_EX_META/MIN3ADD6_CHORD_META";
import MIN3ADD9_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_EX_META/MIN3ADD9_CHORD_META";
import DIM7_CHORD_META from "./CHORD_INSTANCE_META/CHORD7_META/DIM7_CHORD_META";
import DOM7_CHORD_META from "./CHORD_INSTANCE_META/CHORD7_META/DOM7_CHORD_META";
import HALFDIM7_CHORD_META from "./CHORD_INSTANCE_META/CHORD7_META/HALFDIM7_CHORD_META";
import MAJ7_CHORD_META from "./CHORD_INSTANCE_META/CHORD7_META/MAJ7_CHORD_META";
import MIN7_CHORD_META from "./CHORD_INSTANCE_META/CHORD7_META/MIN7_CHORD_META";
import MINMAJ7_CHORD_META from "./CHORD_INSTANCE_META/CHORD7_META/MINMAJ7_CHORD_META";
import DOM7ADD6_CHORD_META from "./CHORD_INSTANCE_META/CHORD7_EX_META/DOM7ADD6_CHORD_META";
import MAJ7ADD11_CHORD_META from "./CHORD_INSTANCE_META/CHORD7_EX_META/MAJ7ADD11_CHORD_META";
import DOM9_CHORD_META from "./CHORD_INSTANCE_META/CHORD9_META/DOM9_CHORD_META";
import MAJ9_CHORD_META from "./CHORD_INSTANCE_META/CHORD9_META/MAJ9_CHORD_META";
import MIN9_CHORD_META from "./CHORD_INSTANCE_META/CHORD9_META/MIN9_CHORD_META";
import MINMAJ9_CHORD_META from "./CHORD_INSTANCE_META/CHORD9_META/MINMAJ9_CHORD_META";
import DOM11_CHORD_META from "./CHORD_INSTANCE_META/CHORD11_META/DOM11_CHORD_META";
import MAJ11_CHORD_META from "./CHORD_INSTANCE_META/CHORD11_META/MAJ11_CHORD_META";
import MIN11_CHORD_META from "./CHORD_INSTANCE_META/CHORD11_META/MIN11_CHORD_META";
import MINMAJ11_CHORD_META from "./CHORD_INSTANCE_META/CHORD11_META/MINMAJ11_CHORD_META";
import DOM13_CHORD_META from "./CHORD_INSTANCE_META/CHORD13_META/DOM13_CHORD_META";
import MAJ13_CHORD_META from "./CHORD_INSTANCE_META/CHORD13_META/MAJ13_CHORD_META";
import MIN13_CHORD_META from "./CHORD_INSTANCE_META/CHORD13_META/MIN13_CHORD_META";
import MINMAJ13_CHORD_META from "./CHORD_INSTANCE_META/CHORD13_META/MINMAJ13_CHORD_META";
import DOM13SUS4_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/DOM13SUS4_CHORD_META";
import DOM7SUS2_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/DOM7SUS2_CHORD_META";
import DOM7SUS4_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/DOM7SUS4_CHORD_META";
import DOM7SUS4_FLAT9_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/DOM7SUS4_FLAT9_CHORD_META";
import DOM9SUS4_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/DOM9SUS4_CHORD_META";
import MAJ13SUS2_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/MAJ13SUS2_CHORD_META";
import MAJ13SUS4_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/MAJ13SUS4_CHORD_META";
import MAJ7SUS2_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/MAJ7SUS2_CHORD_META";
import MAJ7SUS4_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/MAJ7SUS4_CHORD_META";
import MAJ9SUS4_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/MAJ9SUS4_CHORD_META";
import SUS2_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/SUS2_CHORD_META";
import SUS4_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/SUS4_CHORD_META";
import DOM11_FLAT13_CHORD_META from "./CHORD_INSTANCE_META/DOM11_ALTER_META/DOM11_FLAT13_CHORD_META";
import DOM11_FLAT5_CHORD_META from "./CHORD_INSTANCE_META/DOM11_ALTER_META/DOM11_FLAT5_CHORD_META";
import DOM11_FLAT9_CHORD_META from "./CHORD_INSTANCE_META/DOM11_ALTER_META/DOM11_FLAT9_CHORD_META";
import DOM11_SHARP5_CHORD_META from "./CHORD_INSTANCE_META/DOM11_ALTER_META/DOM11_SHARP5_CHORD_META";
import DOM11_SHARP9_CHORD_META from "./CHORD_INSTANCE_META/DOM11_ALTER_META/DOM11_SHARP9_CHORD_META";
import DOM13_FLAT5_CHORD_META from "./CHORD_INSTANCE_META/DOM13_ALTER_META/DOM13_FLAT5_CHORD_META";
import DOM13_FLAT9_CHORD_META from "./CHORD_INSTANCE_META/DOM13_ALTER_META/DOM13_FLAT9_CHORD_META";
import DOM13_SHARP11_CHORD_META from "./CHORD_INSTANCE_META/DOM13_ALTER_META/DOM13_SHARP11_CHORD_META";
import DOM13_SHARP5_CHORD_META from "./CHORD_INSTANCE_META/DOM13_ALTER_META/DOM13_SHARP5_CHORD_META";
import DOM13_SHARP9_CHORD_META from "./CHORD_INSTANCE_META/DOM13_ALTER_META/DOM13_SHARP9_CHORD_META";
import AUGMAJ7_CHORD_META from "./CHORD_INSTANCE_META/DOM7_ALTER_META/AUGMAJ7_CHORD_META";
import DOM7_FLAT13_CHORD_META from "./CHORD_INSTANCE_META/DOM7_ALTER_META/DOM7_FLAT13_CHORD_META";
import DOM7_FLAT5_CHORD_META from "./CHORD_INSTANCE_META/DOM7_ALTER_META/DOM7_FLAT5_CHORD_META";
import DOM7_FLAT5_FLAT9_CHORD_META from "./CHORD_INSTANCE_META/DOM7_ALTER_META/DOM7_FLAT5_FLAT9_CHORD_META";
import DOM7_FLAT5_SHARP9_CHORD_META from "./CHORD_INSTANCE_META/DOM7_ALTER_META/DOM7_FLAT5_SHARP9_CHORD_META";
import DOM7_FLAT9_CHORD_META from "./CHORD_INSTANCE_META/DOM7_ALTER_META/DOM7_FLAT9_CHORD_META";
import DOM7_SHARP11_CHORD_META from "./CHORD_INSTANCE_META/DOM7_ALTER_META/DOM7_SHARP11_CHORD_META";
import DOM7_SHARP5_CHORD_META from "./CHORD_INSTANCE_META/DOM7_ALTER_META/DOM7_SHARP5_CHORD_META";
import DOM7_SHARP5_FLAT9_CHORD_META from "./CHORD_INSTANCE_META/DOM7_ALTER_META/DOM7_SHARP5_FLAT9_CHORD_META";
import DOM7_SHARP5_SHARP9_CHORD_META from "./CHORD_INSTANCE_META/DOM7_ALTER_META/DOM7_SHARP5_SHARP9_CHORD_META";
import DOM7_SHARP9_CHORD_META from "./CHORD_INSTANCE_META/DOM7_ALTER_META/DOM7_SHARP9_CHORD_META";
import DOM9ADD13_CHORD_META from "./CHORD_INSTANCE_META/DOM9_ALTER_META/DOM9ADD13_CHORD_META";
import DOM9_FLAT13_CHORD_META from "./CHORD_INSTANCE_META/DOM9_ALTER_META/DOM9_FLAT13_CHORD_META";
import DOM9_SHARP11_CHORD_META from "./CHORD_INSTANCE_META/DOM9_ALTER_META/DOM9_SHARP11_CHORD_META";
import DOM9_SHARP5_CHORD_META from "./CHORD_INSTANCE_META/DOM9_ALTER_META/DOM9_SHARP5_CHORD_META";
import MAJ13_FLAT5_CHORD_META from "./CHORD_INSTANCE_META/MAJ13_ALTER_META/MAJ13_FLAT5_CHORD_META";
import MAJ13_FLAT9_CHORD_META from "./CHORD_INSTANCE_META/MAJ13_ALTER_META/MAJ13_FLAT9_CHORD_META";
import MAJ13_SHARP11_CHORD_META from "./CHORD_INSTANCE_META/MAJ13_ALTER_META/MAJ13_SHARP11_CHORD_META";
import MAJ13_SHARP5_CHORD_META from "./CHORD_INSTANCE_META/MAJ13_ALTER_META/MAJ13_SHARP5_CHORD_META";
import MAJ7_FLAT13_CHORD_META from "./CHORD_INSTANCE_META/MAJ7_ALTER_META/MAJ7_FLAT13_CHORD_META";
import MAJ7_FLAT5_CHORD_META from "./CHORD_INSTANCE_META/MAJ7_ALTER_META/MAJ7_FLAT5_CHORD_META";
import MAJ7_FLAT9_CHORD_META from "./CHORD_INSTANCE_META/MAJ7_ALTER_META/MAJ7_FLAT9_CHORD_META";
import MAJ7_SHARP11_CHORD_META from "./CHORD_INSTANCE_META/MAJ7_ALTER_META/MAJ7_SHARP11_CHORD_META";
import MAJ9_FLAT13_CHORD_META from "./CHORD_INSTANCE_META/MAJ9_ALTER_META/MAJ9_FLAT13_CHORD_META";
import MAJ9_FLAT5_CHORD_META from "./CHORD_INSTANCE_META/MAJ9_ALTER_META/MAJ9_FLAT5_CHORD_META";
import MAJ9_SHARP11_CHORD_META from "./CHORD_INSTANCE_META/MAJ9_ALTER_META/MAJ9_SHARP11_CHORD_META";
import MAJ9_SHARP5_CHORD_META from "./CHORD_INSTANCE_META/MAJ9_ALTER_META/MAJ9_SHARP5_CHORD_META";
import MIN11_FLAT5_CHORD_META from "./CHORD_INSTANCE_META/MIN11_ALTER_META/MIN11_FLAT5_CHORD_META";
import MIN7_SHARP5_CHORD_META from "./CHORD_INSTANCE_META/MIN7_ALTER_META/MIN7_SHARP5_CHORD_META";
import MINMAJ7_FLAT5_CHORD_META from "./CHORD_INSTANCE_META/MIN7_ALTER_META/MINMAJ7_FLAT5_CHORD_META";
import MINMAJ7_SHARP5_CHORD_META from "./CHORD_INSTANCE_META/MIN7_ALTER_META/MINMAJ7_SHARP5_CHORD_META";
import MIN9_FLAT5_CHORD_META from "./CHORD_INSTANCE_META/MIN9_ALTER_META/MIN9_FLAT5_CHORD_META";

/**
 * 所有和弦实例元数据的扁平化数组
 * 包含所有和弦公式在所有 12 个根音上的实例数据
 *
 * 使用展开运算符 (...) 将每个和弦类型的实例数组扁平化
 *
 * 注意：这里必须在变量声明处显式标注类型（而非末尾 `as` 断言）。
 * 否则 TS 会对 87 个 spread 展开后的字面量做联合类型推断，规模超出上限触发 TS2590。
 * 显式标注让 TS 直接按 I_ChordInstanceMeta[] 推断，绕过字面量联合爆炸。
 */
const ALL_CHORD_INSTANCE_META: I_ChordInstanceMeta[] = [
  ...AUG3_CHORD_META,
  ...DIM3_CHORD_META,
  ...MAJ3_CHORD_META,
  ...MAJ3_FLAT5_CHORD_META,
  ...MIN3_CHORD_META,
  ...MAJ3ADD11_CHORD_META,
  ...MAJ3ADD6ADD9_CHORD_META,
  ...MAJ3ADD6_CHORD_META,
  ...MAJ3ADD9_CHORD_META,
  ...MIN3ADD11_CHORD_META,
  ...MIN3ADD6ADD9_CHORD_META,
  ...MIN3ADD6_CHORD_META,
  ...MIN3ADD9_CHORD_META,
  ...DIM7_CHORD_META,
  ...DOM7_CHORD_META,
  ...HALFDIM7_CHORD_META,
  ...MAJ7_CHORD_META,
  ...MIN7_CHORD_META,
  ...MINMAJ7_CHORD_META,
  ...DOM7ADD6_CHORD_META,
  ...MAJ7ADD11_CHORD_META,
  ...DOM9_CHORD_META,
  ...MAJ9_CHORD_META,
  ...MIN9_CHORD_META,
  ...MINMAJ9_CHORD_META,
  ...DOM11_CHORD_META,
  ...MAJ11_CHORD_META,
  ...MIN11_CHORD_META,
  ...MINMAJ11_CHORD_META,
  ...DOM13_CHORD_META,
  ...MAJ13_CHORD_META,
  ...MIN13_CHORD_META,
  ...MINMAJ13_CHORD_META,
  ...DOM13SUS4_CHORD_META,
  ...DOM7SUS2_CHORD_META,
  ...DOM7SUS4_CHORD_META,
  ...DOM7SUS4_FLAT9_CHORD_META,
  ...DOM9SUS4_CHORD_META,
  ...MAJ13SUS2_CHORD_META,
  ...MAJ13SUS4_CHORD_META,
  ...MAJ7SUS2_CHORD_META,
  ...MAJ7SUS4_CHORD_META,
  ...MAJ9SUS4_CHORD_META,
  ...SUS2_CHORD_META,
  ...SUS4_CHORD_META,
  ...DOM11_FLAT13_CHORD_META,
  ...DOM11_FLAT5_CHORD_META,
  ...DOM11_FLAT9_CHORD_META,
  ...DOM11_SHARP5_CHORD_META,
  ...DOM11_SHARP9_CHORD_META,
  ...DOM13_FLAT5_CHORD_META,
  ...DOM13_FLAT9_CHORD_META,
  ...DOM13_SHARP11_CHORD_META,
  ...DOM13_SHARP5_CHORD_META,
  ...DOM13_SHARP9_CHORD_META,
  ...AUGMAJ7_CHORD_META,
  ...DOM7_FLAT13_CHORD_META,
  ...DOM7_FLAT5_CHORD_META,
  ...DOM7_FLAT5_FLAT9_CHORD_META,
  ...DOM7_FLAT5_SHARP9_CHORD_META,
  ...DOM7_FLAT9_CHORD_META,
  ...DOM7_SHARP11_CHORD_META,
  ...DOM7_SHARP5_CHORD_META,
  ...DOM7_SHARP5_FLAT9_CHORD_META,
  ...DOM7_SHARP5_SHARP9_CHORD_META,
  ...DOM7_SHARP9_CHORD_META,
  ...DOM9ADD13_CHORD_META,
  ...DOM9_FLAT13_CHORD_META,
  ...DOM9_SHARP11_CHORD_META,
  ...DOM9_SHARP5_CHORD_META,
  ...MAJ13_FLAT5_CHORD_META,
  ...MAJ13_FLAT9_CHORD_META,
  ...MAJ13_SHARP11_CHORD_META,
  ...MAJ13_SHARP5_CHORD_META,
  ...MAJ7_FLAT13_CHORD_META,
  ...MAJ7_FLAT5_CHORD_META,
  ...MAJ7_FLAT9_CHORD_META,
  ...MAJ7_SHARP11_CHORD_META,
  ...MAJ9_FLAT13_CHORD_META,
  ...MAJ9_FLAT5_CHORD_META,
  ...MAJ9_SHARP11_CHORD_META,
  ...MAJ9_SHARP5_CHORD_META,
  ...MIN11_FLAT5_CHORD_META,
  ...MIN7_SHARP5_CHORD_META,
  ...MINMAJ7_FLAT5_CHORD_META,
  ...MINMAJ7_SHARP5_CHORD_META,
  ...MIN9_FLAT5_CHORD_META,
];

export default ALL_CHORD_INSTANCE_META;
