/**
 * 按 chordFormulaId 索引的映射表
 * 键为 chordFormulaId，值为该和弦公式在所有根音上的实例数组
 */

import { I_ChordInstanceMeta } from "./types";
import AUG3_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_META/AUG3_CHORD_META";
import DIM3_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_META/DIM3_CHORD_META";
import MAJ3_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_META/MAJ3_CHORD_META";
import MAJ3_FLAT5_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_META/MAJ3_FLAT5_CHORD_META";
import MIN3_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_META/MIN3_CHORD_META";
import MAJ3ADD11_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_EX_META/MAJ3ADD11_CHORD_META";
import MAJ3ADD6ADD9_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_EX_META/MAJ3ADD6ADD9_CHORD_META";
import MAJ3ADD6_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_EX_META/MAJ3ADD6_CHORD_META";
import MAJ3ADD9_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_EX_META/MAJ3ADD9_CHORD_META";
import MIN3ADD11_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_EX_META/MIN3ADD11_CHORD_META";
import MIN3ADD6ADD9_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_EX_META/MIN3ADD6ADD9_CHORD_META";
import MIN3ADD6_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_EX_META/MIN3ADD6_CHORD_META";
import MIN3ADD9_CHORD_META from "./CHORD_INSTANCE_META/CHORD3_EX_META/MIN3ADD9_CHORD_META";
import DIM7_CHORD_META from "./CHORD_INSTANCE_META/CHORD7_META/DIM7_CHORD_META";
import DOM7_CHORD_META from "./CHORD_INSTANCE_META/CHORD7_META/DOM7_CHORD_META";
import HALFDIM7_CHORD_META from "./CHORD_INSTANCE_META/CHORD7_META/HALFDIM7_CHORD_META";
import MAJ7_CHORD_META from "./CHORD_INSTANCE_META/CHORD7_META/MAJ7_CHORD_META";
import MIN7_CHORD_META from "./CHORD_INSTANCE_META/CHORD7_META/MIN7_CHORD_META";
import MINMAJ7_CHORD_META from "./CHORD_INSTANCE_META/CHORD7_META/MINMAJ7_CHORD_META";
import DOM7ADD6_CHORD_META from "./CHORD_INSTANCE_META/CHORD7_EX_META/DOM7ADD6_CHORD_META";
import MAJ7ADD11_CHORD_META from "./CHORD_INSTANCE_META/CHORD7_EX_META/MAJ7ADD11_CHORD_META";
import DOM9_CHORD_META from "./CHORD_INSTANCE_META/CHORD9_META/DOM9_CHORD_META";
import MAJ9_CHORD_META from "./CHORD_INSTANCE_META/CHORD9_META/MAJ9_CHORD_META";
import MIN9_CHORD_META from "./CHORD_INSTANCE_META/CHORD9_META/MIN9_CHORD_META";
import MINMAJ9_CHORD_META from "./CHORD_INSTANCE_META/CHORD9_META/MINMAJ9_CHORD_META";
import DOM11_CHORD_META from "./CHORD_INSTANCE_META/CHORD11_META/DOM11_CHORD_META";
import MAJ11_CHORD_META from "./CHORD_INSTANCE_META/CHORD11_META/MAJ11_CHORD_META";
import MIN11_CHORD_META from "./CHORD_INSTANCE_META/CHORD11_META/MIN11_CHORD_META";
import MINMAJ11_CHORD_META from "./CHORD_INSTANCE_META/CHORD11_META/MINMAJ11_CHORD_META";
import DOM13_CHORD_META from "./CHORD_INSTANCE_META/CHORD13_META/DOM13_CHORD_META";
import MAJ13_CHORD_META from "./CHORD_INSTANCE_META/CHORD13_META/MAJ13_CHORD_META";
import MIN13_CHORD_META from "./CHORD_INSTANCE_META/CHORD13_META/MIN13_CHORD_META";
import MINMAJ13_CHORD_META from "./CHORD_INSTANCE_META/CHORD13_META/MINMAJ13_CHORD_META";
import DOM13SUS4_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/DOM13SUS4_CHORD_META";
import DOM7SUS2_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/DOM7SUS2_CHORD_META";
import DOM7SUS4_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/DOM7SUS4_CHORD_META";
import DOM7SUS4_FLAT9_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/DOM7SUS4_FLAT9_CHORD_META";
import DOM9SUS4_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/DOM9SUS4_CHORD_META";
import MAJ13SUS2_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/MAJ13SUS2_CHORD_META";
import MAJ13SUS4_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/MAJ13SUS4_CHORD_META";
import MAJ7SUS2_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/MAJ7SUS2_CHORD_META";
import MAJ7SUS4_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/MAJ7SUS4_CHORD_META";
import MAJ9SUS4_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/MAJ9SUS4_CHORD_META";
import SUS2_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/SUS2_CHORD_META";
import SUS4_CHORD_META from "./CHORD_INSTANCE_META/CHORD_SUS_META/SUS4_CHORD_META";
import DOM11_FLAT13_CHORD_META from "./CHORD_INSTANCE_META/DOM11_ALTER_META/DOM11_FLAT13_CHORD_META";
import DOM11_FLAT5_CHORD_META from "./CHORD_INSTANCE_META/DOM11_ALTER_META/DOM11_FLAT5_CHORD_META";
import DOM11_FLAT9_CHORD_META from "./CHORD_INSTANCE_META/DOM11_ALTER_META/DOM11_FLAT9_CHORD_META";
import DOM11_SHARP5_CHORD_META from "./CHORD_INSTANCE_META/DOM11_ALTER_META/DOM11_SHARP5_CHORD_META";
import DOM11_SHARP9_CHORD_META from "./CHORD_INSTANCE_META/DOM11_ALTER_META/DOM11_SHARP9_CHORD_META";
import DOM13_FLAT5_CHORD_META from "./CHORD_INSTANCE_META/DOM13_ALTER_META/DOM13_FLAT5_CHORD_META";
import DOM13_FLAT9_CHORD_META from "./CHORD_INSTANCE_META/DOM13_ALTER_META/DOM13_FLAT9_CHORD_META";
import DOM13_SHARP11_CHORD_META from "./CHORD_INSTANCE_META/DOM13_ALTER_META/DOM13_SHARP11_CHORD_META";
import DOM13_SHARP5_CHORD_META from "./CHORD_INSTANCE_META/DOM13_ALTER_META/DOM13_SHARP5_CHORD_META";
import DOM13_SHARP9_CHORD_META from "./CHORD_INSTANCE_META/DOM13_ALTER_META/DOM13_SHARP9_CHORD_META";
import AUGMAJ7_CHORD_META from "./CHORD_INSTANCE_META/DOM7_ALTER_META/AUGMAJ7_CHORD_META";
import DOM7_FLAT13_CHORD_META from "./CHORD_INSTANCE_META/DOM7_ALTER_META/DOM7_FLAT13_CHORD_META";
import DOM7_FLAT5_CHORD_META from "./CHORD_INSTANCE_META/DOM7_ALTER_META/DOM7_FLAT5_CHORD_META";
import DOM7_FLAT5_FLAT9_CHORD_META from "./CHORD_INSTANCE_META/DOM7_ALTER_META/DOM7_FLAT5_FLAT9_CHORD_META";
import DOM7_FLAT5_SHARP9_CHORD_META from "./CHORD_INSTANCE_META/DOM7_ALTER_META/DOM7_FLAT5_SHARP9_CHORD_META";
import DOM7_FLAT9_CHORD_META from "./CHORD_INSTANCE_META/DOM7_ALTER_META/DOM7_FLAT9_CHORD_META";
import DOM7_SHARP11_CHORD_META from "./CHORD_INSTANCE_META/DOM7_ALTER_META/DOM7_SHARP11_CHORD_META";
import DOM7_SHARP5_CHORD_META from "./CHORD_INSTANCE_META/DOM7_ALTER_META/DOM7_SHARP5_CHORD_META";
import DOM7_SHARP5_FLAT9_CHORD_META from "./CHORD_INSTANCE_META/DOM7_ALTER_META/DOM7_SHARP5_FLAT9_CHORD_META";
import DOM7_SHARP5_SHARP9_CHORD_META from "./CHORD_INSTANCE_META/DOM7_ALTER_META/DOM7_SHARP5_SHARP9_CHORD_META";
import DOM7_SHARP9_CHORD_META from "./CHORD_INSTANCE_META/DOM7_ALTER_META/DOM7_SHARP9_CHORD_META";
import DOM9ADD13_CHORD_META from "./CHORD_INSTANCE_META/DOM9_ALTER_META/DOM9ADD13_CHORD_META";
import DOM9_FLAT13_CHORD_META from "./CHORD_INSTANCE_META/DOM9_ALTER_META/DOM9_FLAT13_CHORD_META";
import DOM9_SHARP11_CHORD_META from "./CHORD_INSTANCE_META/DOM9_ALTER_META/DOM9_SHARP11_CHORD_META";
import DOM9_SHARP5_CHORD_META from "./CHORD_INSTANCE_META/DOM9_ALTER_META/DOM9_SHARP5_CHORD_META";
import MAJ13_FLAT5_CHORD_META from "./CHORD_INSTANCE_META/MAJ13_ALTER_META/MAJ13_FLAT5_CHORD_META";
import MAJ13_FLAT9_CHORD_META from "./CHORD_INSTANCE_META/MAJ13_ALTER_META/MAJ13_FLAT9_CHORD_META";
import MAJ13_SHARP11_CHORD_META from "./CHORD_INSTANCE_META/MAJ13_ALTER_META/MAJ13_SHARP11_CHORD_META";
import MAJ13_SHARP5_CHORD_META from "./CHORD_INSTANCE_META/MAJ13_ALTER_META/MAJ13_SHARP5_CHORD_META";
import MAJ7_FLAT13_CHORD_META from "./CHORD_INSTANCE_META/MAJ7_ALTER_META/MAJ7_FLAT13_CHORD_META";
import MAJ7_FLAT5_CHORD_META from "./CHORD_INSTANCE_META/MAJ7_ALTER_META/MAJ7_FLAT5_CHORD_META";
import MAJ7_FLAT9_CHORD_META from "./CHORD_INSTANCE_META/MAJ7_ALTER_META/MAJ7_FLAT9_CHORD_META";
import MAJ7_SHARP11_CHORD_META from "./CHORD_INSTANCE_META/MAJ7_ALTER_META/MAJ7_SHARP11_CHORD_META";
import MAJ9_FLAT13_CHORD_META from "./CHORD_INSTANCE_META/MAJ9_ALTER_META/MAJ9_FLAT13_CHORD_META";
import MAJ9_FLAT5_CHORD_META from "./CHORD_INSTANCE_META/MAJ9_ALTER_META/MAJ9_FLAT5_CHORD_META";
import MAJ9_SHARP11_CHORD_META from "./CHORD_INSTANCE_META/MAJ9_ALTER_META/MAJ9_SHARP11_CHORD_META";
import MAJ9_SHARP5_CHORD_META from "./CHORD_INSTANCE_META/MAJ9_ALTER_META/MAJ9_SHARP5_CHORD_META";
import MIN11_FLAT5_CHORD_META from "./CHORD_INSTANCE_META/MIN11_ALTER_META/MIN11_FLAT5_CHORD_META";
import MIN7_SHARP5_CHORD_META from "./CHORD_INSTANCE_META/MIN7_ALTER_META/MIN7_SHARP5_CHORD_META";
import MINMAJ7_FLAT5_CHORD_META from "./CHORD_INSTANCE_META/MIN7_ALTER_META/MINMAJ7_FLAT5_CHORD_META";
import MINMAJ7_SHARP5_CHORD_META from "./CHORD_INSTANCE_META/MIN7_ALTER_META/MINMAJ7_SHARP5_CHORD_META";
import MIN9_FLAT5_CHORD_META from "./CHORD_INSTANCE_META/MIN9_ALTER_META/MIN9_FLAT5_CHORD_META";

export const CHORD_INSTANCE_META_MAP: Record<string, I_ChordInstanceMeta[]> = {
  aug3: AUG3_CHORD_META,
  dim3: DIM3_CHORD_META,
  maj3: MAJ3_CHORD_META,
  maj3_b5: MAJ3_FLAT5_CHORD_META,
  min3: MIN3_CHORD_META,
  maj3add11: MAJ3ADD11_CHORD_META,
  maj3add6add9: MAJ3ADD6ADD9_CHORD_META,
  maj3add6: MAJ3ADD6_CHORD_META,
  maj3add9: MAJ3ADD9_CHORD_META,
  min3add11: MIN3ADD11_CHORD_META,
  min3add6add9: MIN3ADD6ADD9_CHORD_META,
  min3add6: MIN3ADD6_CHORD_META,
  min3add9: MIN3ADD9_CHORD_META,
  dim7: DIM7_CHORD_META,
  dom7: DOM7_CHORD_META,
  halfdim7: HALFDIM7_CHORD_META,
  maj7: MAJ7_CHORD_META,
  min7: MIN7_CHORD_META,
  minmaj7: MINMAJ7_CHORD_META,
  dom7add6: DOM7ADD6_CHORD_META,
  maj7add11: MAJ7ADD11_CHORD_META,
  dom9: DOM9_CHORD_META,
  maj9: MAJ9_CHORD_META,
  min9: MIN9_CHORD_META,
  minmaj9: MINMAJ9_CHORD_META,
  dom11: DOM11_CHORD_META,
  maj11: MAJ11_CHORD_META,
  min11: MIN11_CHORD_META,
  minmaj11: MINMAJ11_CHORD_META,
  dom13: DOM13_CHORD_META,
  maj13: MAJ13_CHORD_META,
  min13: MIN13_CHORD_META,
  minmaj13: MINMAJ13_CHORD_META,
  dom13sus4: DOM13SUS4_CHORD_META,
  dom7sus2: DOM7SUS2_CHORD_META,
  dom7sus4: DOM7SUS4_CHORD_META,
  dom7sus4_b9: DOM7SUS4_FLAT9_CHORD_META,
  dom9sus4: DOM9SUS4_CHORD_META,
  maj13sus2: MAJ13SUS2_CHORD_META,
  maj13sus4: MAJ13SUS4_CHORD_META,
  maj7sus2: MAJ7SUS2_CHORD_META,
  maj7sus4: MAJ7SUS4_CHORD_META,
  maj9sus4: MAJ9SUS4_CHORD_META,
  sus2: SUS2_CHORD_META,
  sus4: SUS4_CHORD_META,
  dom11_b13: DOM11_FLAT13_CHORD_META,
  dom11_b5: DOM11_FLAT5_CHORD_META,
  dom11_b9: DOM11_FLAT9_CHORD_META,
  "dom11_#5": DOM11_SHARP5_CHORD_META,
  "dom11_#9": DOM11_SHARP9_CHORD_META,
  dom13_b5: DOM13_FLAT5_CHORD_META,
  dom13_b9: DOM13_FLAT9_CHORD_META,
  "dom13_#11": DOM13_SHARP11_CHORD_META,
  "dom13_#5": DOM13_SHARP5_CHORD_META,
  "dom13_#9": DOM13_SHARP9_CHORD_META,
  augmaj7: AUGMAJ7_CHORD_META,
  dom7_b13: DOM7_FLAT13_CHORD_META,
  dom7_b5: DOM7_FLAT5_CHORD_META,
  dom7_b5_flat9: DOM7_FLAT5_FLAT9_CHORD_META,
  "dom7_b5_#9": DOM7_FLAT5_SHARP9_CHORD_META,
  dom7_b9: DOM7_FLAT9_CHORD_META,
  "dom7_#11": DOM7_SHARP11_CHORD_META,
  "dom7_#5": DOM7_SHARP5_CHORD_META,
  "dom7_#5_b9": DOM7_SHARP5_FLAT9_CHORD_META,
  "dom7_#5_sharp9": DOM7_SHARP5_SHARP9_CHORD_META,
  "dom7_#9": DOM7_SHARP9_CHORD_META,
  dom9add13: DOM9ADD13_CHORD_META,
  dom9_b13: DOM9_FLAT13_CHORD_META,
  "dom9_#11": DOM9_SHARP11_CHORD_META,
  "dom9_#5": DOM9_SHARP5_CHORD_META,
  maj13_b5: MAJ13_FLAT5_CHORD_META,
  maj13_b9: MAJ13_FLAT9_CHORD_META,
  "maj13_#11": MAJ13_SHARP11_CHORD_META,
  "maj13_#5": MAJ13_SHARP5_CHORD_META,
  maj7_b13: MAJ7_FLAT13_CHORD_META,
  maj7_b5: MAJ7_FLAT5_CHORD_META,
  maj7_b9: MAJ7_FLAT9_CHORD_META,
  "maj7_#11": MAJ7_SHARP11_CHORD_META,
  maj9_b13: MAJ9_FLAT13_CHORD_META,
  maj9_b5: MAJ9_FLAT5_CHORD_META,
  "maj9_#11": MAJ9_SHARP11_CHORD_META,
  "maj9_#5": MAJ9_SHARP5_CHORD_META,
  min11_b5: MIN11_FLAT5_CHORD_META,
  "min7_#5": MIN7_SHARP5_CHORD_META,
  minmaj7_b5: MINMAJ7_FLAT5_CHORD_META,
  "minmaj7_#5": MINMAJ7_SHARP5_CHORD_META,
  min9_b5: MIN9_FLAT5_CHORD_META,
} as Record<string, I_ChordInstanceMeta[]>;
