// 调式实例聚合数据
// 从 SCALE_INSTANCE_META 中所有调式文件聚合而成

import NATURAL_MAJOR_SCALE_META from "./SCALE_INSTANCE_META/DIATONIC_MODE_META/NATURAL_MAJOR_SCALE_META"
import DORIAN_SCALE_META from "./SCALE_INSTANCE_META/DIATONIC_MODE_META/DORIAN_SCALE_META"
import PHRYGIAN_SCALE_META from "./SCALE_INSTANCE_META/DIATONIC_MODE_META/PHRYGIAN_SCALE_META"
import LYDIAN_SCALE_META from "./SCALE_INSTANCE_META/DIATONIC_MODE_META/LYDIAN_SCALE_META"
import MIXOLYDIAN_SCALE_META from "./SCALE_INSTANCE_META/DIATONIC_MODE_META/MIXOLYDIAN_SCALE_META"
import NATURAL_MINOR_SCALE_META from "./SCALE_INSTANCE_META/DIATONIC_MODE_META/NATURAL_MINOR_SCALE_META"
import LOCRIAN_SCALE_META from "./SCALE_INSTANCE_META/DIATONIC_MODE_META/LOCRIAN_SCALE_META"
import HARMONIC_MAJOR_SCALE_META from "./SCALE_INSTANCE_META/HARMONIC_MAJOR_MODE_META/HARMONIC_MAJOR_SCALE_META"
import MELODIC_MAJOR_DESCENDING_SCALE_META from "./SCALE_INSTANCE_META/MELODIC_MAJOR_MODE_META/MELODIC_MAJOR_DESCENDING_SCALE_META"
import HARMONIC_MINOR_SCALE_META from "./SCALE_INSTANCE_META/HARMONIC_MINOR_MODE_META/HARMONIC_MINOR_SCALE_META"
import LOCRIAN_SHARP6_SCALE_META from "./SCALE_INSTANCE_META/HARMONIC_MINOR_MODE_META/LOCRIAN_SHARP6_SCALE_META"
import IONIAN_SHARP5_SCALE_META from "./SCALE_INSTANCE_META/HARMONIC_MINOR_MODE_META/IONIAN_SHARP5_SCALE_META"
import DORIAN_SHARP4_SCALE_META from "./SCALE_INSTANCE_META/HARMONIC_MINOR_MODE_META/DORIAN_SHARP4_SCALE_META"
import PHRYGIAN_DOMINANT_SCALE_META from "./SCALE_INSTANCE_META/HARMONIC_MINOR_MODE_META/PHRYGIAN_DOMINANT_SCALE_META"
import LYDIAN_SHARP2_SCALE_META from "./SCALE_INSTANCE_META/HARMONIC_MINOR_MODE_META/LYDIAN_SHARP2_SCALE_META"
import MELODIC_MINOR_ASCENDING_SCALE_META from "./SCALE_INSTANCE_META/MELODIC_MINOR_MODE_META/MELODIC_MINOR_ASCENDING_SCALE_META"
import DORIAN_FLAT2_SCALE_META from "./SCALE_INSTANCE_META/MELODIC_MINOR_MODE_META/DORIAN_FLAT2_SCALE_META"
import LYDIAN_AUGMENTED_SCALE_META from "./SCALE_INSTANCE_META/MELODIC_MINOR_MODE_META/LYDIAN_AUGMENTED_SCALE_META"
import LYDIAN_DOMINANT_SCALE_META from "./SCALE_INSTANCE_META/MELODIC_MINOR_MODE_META/LYDIAN_DOMINANT_SCALE_META"
import LOCRIAN_SHARP2_SCALE_META from "./SCALE_INSTANCE_META/MELODIC_MINOR_MODE_META/LOCRIAN_SHARP2_SCALE_META"
import DOUBLE_HARMONIC_MAJOR_SCALE_META from "./SCALE_INSTANCE_META/DOUBLE_HARMONIC_MODE_META/DOUBLE_HARMONIC_MAJOR_SCALE_META"
import HUNGARIAN_MINOR_SCALE_META from "./SCALE_INSTANCE_META/DOUBLE_HARMONIC_MODE_META/HUNGARIAN_MINOR_SCALE_META"
import ORIENTAL_SCALE_META from "./SCALE_INSTANCE_META/DOUBLE_HARMONIC_MODE_META/ORIENTAL_SCALE_META"
import IONIAN_SHARP2_SHARP5_SCALE_META from "./SCALE_INSTANCE_META/DOUBLE_HARMONIC_MODE_META/IONIAN_SHARP2_SHARP5_SCALE_META"
import GONG_SCALE_META from "./SCALE_INSTANCE_META/CHINESE_PENTATONIC_MODE_META/GONG_SCALE_META"
import SHANG_SCALE_META from "./SCALE_INSTANCE_META/CHINESE_PENTATONIC_MODE_META/SHANG_SCALE_META"
import JUE_SCALE_META from "./SCALE_INSTANCE_META/CHINESE_PENTATONIC_MODE_META/JUE_SCALE_META"
import ZHI_SCALE_META from "./SCALE_INSTANCE_META/CHINESE_PENTATONIC_MODE_META/ZHI_SCALE_META"
import YU_SCALE_META from "./SCALE_INSTANCE_META/CHINESE_PENTATONIC_MODE_META/YU_SCALE_META"
import YA_YUE_GONG_SCALE_META from "./SCALE_INSTANCE_META/CHINESE_YAYUE_MODE_META/YA_YUE_GONG_SCALE_META"
import YA_YUE_SHANG_SCALE_META from "./SCALE_INSTANCE_META/CHINESE_YAYUE_MODE_META/YA_YUE_SHANG_SCALE_META"
import YA_YUE_JUE_SCALE_META from "./SCALE_INSTANCE_META/CHINESE_YAYUE_MODE_META/YA_YUE_JUE_SCALE_META"
import YA_YUE_ZHI_SCALE_META from "./SCALE_INSTANCE_META/CHINESE_YAYUE_MODE_META/YA_YUE_ZHI_SCALE_META"
import YA_YUE_YU_SCALE_META from "./SCALE_INSTANCE_META/CHINESE_YAYUE_MODE_META/YA_YUE_YU_SCALE_META"
import QING_YUE_GONG_SCALE_META from "./SCALE_INSTANCE_META/CHINESE_QINGYUE_MODE_META/QING_YUE_GONG_SCALE_META"
import QING_YUE_SHANG_SCALE_META from "./SCALE_INSTANCE_META/CHINESE_QINGYUE_MODE_META/QING_YUE_SHANG_SCALE_META"
import QING_YUE_JUE_SCALE_META from "./SCALE_INSTANCE_META/CHINESE_QINGYUE_MODE_META/QING_YUE_JUE_SCALE_META"
import QING_YUE_ZHI_SCALE_META from "./SCALE_INSTANCE_META/CHINESE_QINGYUE_MODE_META/QING_YUE_ZHI_SCALE_META"
import QING_YUE_YU_SCALE_META from "./SCALE_INSTANCE_META/CHINESE_QINGYUE_MODE_META/QING_YUE_YU_SCALE_META"
import YAN_YUE_GONG_SCALE_META from "./SCALE_INSTANCE_META/CHINESE_YANYUE_MODE_META/YAN_YUE_GONG_SCALE_META"
import YAN_YUE_SHANG_SCALE_META from "./SCALE_INSTANCE_META/CHINESE_YANYUE_MODE_META/YAN_YUE_SHANG_SCALE_META"
import YAN_YUE_JUE_SCALE_META from "./SCALE_INSTANCE_META/CHINESE_YANYUE_MODE_META/YAN_YUE_JUE_SCALE_META"
import YAN_YUE_ZHI_SCALE_META from "./SCALE_INSTANCE_META/CHINESE_YANYUE_MODE_META/YAN_YUE_ZHI_SCALE_META"
import YAN_YUE_YU_SCALE_META from "./SCALE_INSTANCE_META/CHINESE_YANYUE_MODE_META/YAN_YUE_YU_SCALE_META"

/**
 * 调式实例数据结构
 */
export type I_ScaleInstance = {
	/** 根音的钢琴键 ID (0-11) */
	pianoKeyIdRoot: number
	/** 调式 ID（如 "NATURAL_MAJOR", "DORIAN" 等） */
	scaleModeId: string
	/** 音阶所有音符的钢琴键 ID 列表 */
	pianoKeyIds: number[]
	/** 排序后的音符列表 */
	pianoKeyIdsSorted: number[]
	/** 度数到钢琴键 ID 的映射 */
	degreeToPianoKeyId: Record<number, number>
	/** 钢琴键 ID 到度数的映射 */
	pianoKeyIdToDegree: Record<number, number | null>
	/** 各音级的变音值（相对于自然音级） */
	degreeAlterationsMap: Record<number, number>
	/** 完整的调式元数据对象（序列化后类型为 any） */
	scaleMode: any
}

// 聚合所有调式实例
const ALL_SCALE_META = [
	...NATURAL_MAJOR_SCALE_META,
	...DORIAN_SCALE_META,
	...PHRYGIAN_SCALE_META,
	...LYDIAN_SCALE_META,
	...MIXOLYDIAN_SCALE_META,
	...NATURAL_MINOR_SCALE_META,
	...LOCRIAN_SCALE_META,
	...HARMONIC_MAJOR_SCALE_META,
	...MELODIC_MAJOR_DESCENDING_SCALE_META,
	...HARMONIC_MINOR_SCALE_META,
	...LOCRIAN_SHARP6_SCALE_META,
	...IONIAN_SHARP5_SCALE_META,
	...DORIAN_SHARP4_SCALE_META,
	...PHRYGIAN_DOMINANT_SCALE_META,
	...LYDIAN_SHARP2_SCALE_META,
	...MELODIC_MINOR_ASCENDING_SCALE_META,
	...DORIAN_FLAT2_SCALE_META,
	...LYDIAN_AUGMENTED_SCALE_META,
	...LYDIAN_DOMINANT_SCALE_META,
	...LOCRIAN_SHARP2_SCALE_META,
	...DOUBLE_HARMONIC_MAJOR_SCALE_META,
	...HUNGARIAN_MINOR_SCALE_META,
	...ORIENTAL_SCALE_META,
	...IONIAN_SHARP2_SHARP5_SCALE_META,
	...GONG_SCALE_META,
	...SHANG_SCALE_META,
	...JUE_SCALE_META,
	...ZHI_SCALE_META,
	...YU_SCALE_META,
	...YA_YUE_GONG_SCALE_META,
	...YA_YUE_SHANG_SCALE_META,
	...YA_YUE_JUE_SCALE_META,
	...YA_YUE_ZHI_SCALE_META,
	...YA_YUE_YU_SCALE_META,
	...QING_YUE_GONG_SCALE_META,
	...QING_YUE_SHANG_SCALE_META,
	...QING_YUE_JUE_SCALE_META,
	...QING_YUE_ZHI_SCALE_META,
	...QING_YUE_YU_SCALE_META,
	...YAN_YUE_GONG_SCALE_META,
	...YAN_YUE_SHANG_SCALE_META,
	...YAN_YUE_JUE_SCALE_META,
	...YAN_YUE_ZHI_SCALE_META,
	...YAN_YUE_YU_SCALE_META,
]

/**
 * 根据 rootPianoKeyId 和 scaleModeId 获取调式实例
 * @param rootPianoKeyId 根音的钢琴键 ID (0-11)
 * @param scaleModeId 调式 ID
 * @returns 调式实例，如果未找到返回 undefined
 */
export const getScaleInstance = (
	rootPianoKeyId: number,
	scaleModeId: string
): I_ScaleInstance | undefined => {
	return ALL_SCALE_META.find(
		(s) => s.pianoKeyIdRoot === rootPianoKeyId && s.scaleModeId === scaleModeId
	)
}

export default ALL_SCALE_META
