import collect from 'collect.js';

interface I_NoteMetaItem {
  uid: number;
  artName: string;
  step: string;
  alter: number;
  semitone: number;
  stepId: number;
  fifthValue: number;
  pianoKeyId: number;
  isNormal: boolean;
  isBlack: boolean;
  mathName: string;
}

const noteMeta = collect<I_NoteMetaItem>([
  {
    uid: 1,
    artName: "C",
    step: "C",
    alter: 0,
    semitone: 0,
    stepId: 0,
    fifthValue: 0,
    pianoKeyId: 0,
    isNormal: true,
    isBlack: false,
    mathName: "C"
  },
  {
    uid: 2,
    artName: "D",
    step: "D",
    alter: 0,
    semitone: 2,
    stepId: 1,
    fifthValue: 2,
    pianoKeyId: 2,
    isNormal: true,
    isBlack: false,
    mathName: "D"
  },
  {
    uid: 3,
    artName: "E",
    step: "E",
    alter: 0,
    semitone: 4,
    stepId: 2,
    fifthValue: 4,
    pianoKeyId: 4,
    isNormal: true,
    isBlack: false,
    mathName: "E"
  },
  {
    uid: 4,
    artName: "F",
    step: "F",
    alter: 0,
    semitone: 5,
    stepId: 3,
    fifthValue: -1,
    pianoKeyId: 5,
    isNormal: true,
    isBlack: false,
    mathName: "F"
  },
  {
    uid: 5,
    artName: "G",
    step: "G",
    alter: 0,
    semitone: 7,
    stepId: 4,
    fifthValue: 1,
    pianoKeyId: 7,
    isNormal: true,
    isBlack: false,
    mathName: "G"
  },
  {
    uid: 6,
    artName: "A",
    step: "A",
    alter: 0,
    semitone: 9,
    stepId: 5,
    fifthValue: 3,
    pianoKeyId: 9,
    isNormal: true,
    isBlack: false,
    mathName: "A"
  },
  {
    uid: 7,
    artName: "B",
    step: "B",
    alter: 0,
    semitone: 11,
    stepId: 6,
    fifthValue: 5,
    pianoKeyId: 11,
    isNormal: true,
    isBlack: false,
    mathName: "B"
  },
  {
    uid: 8,
    artName: "C♯",
    step: "C",
    alter: 1,
    semitone: 1,
    stepId: 0,
    fifthValue: 7,
    pianoKeyId: 1,
    isNormal: true,
    isBlack: true,
    mathName: "C+1"
  },
  {
    uid: 9,
    artName: "C♭",
    step: "C",
    alter: -1,
    semitone: -1,
    stepId: 0,
    fifthValue: -7,
    pianoKeyId: 11,
    isNormal: false,
    isBlack: false,
    mathName: "C-1"
  },
  {
    uid: 10,
    artName: "D♯",
    step: "D",
    alter: 1,
    semitone: 3,
    stepId: 1,
    fifthValue: 9,
    pianoKeyId: 3,
    isNormal: true,
    isBlack: true,
    mathName: "D+1"
  },
  {
    uid: 11,
    artName: "D♭",
    step: "D",
    alter: -1,
    semitone: 1,
    stepId: 1,
    fifthValue: -5,
    pianoKeyId: 1,
    isNormal: true,
    isBlack: true,
    mathName: "D-1"
  },
  {
    uid: 12,
    artName: "E♯",
    step: "E",
    alter: 1,
    semitone: 5,
    stepId: 2,
    fifthValue: 11,
    pianoKeyId: 5,
    isNormal: false,
    isBlack: false,
    mathName: "E+1"
  },
  {
    uid: 13,
    artName: "E♭",
    step: "E",
    alter: -1,
    semitone: 3,
    stepId: 2,
    fifthValue: -3,
    pianoKeyId: 3,
    isNormal: true,
    isBlack: true,
    mathName: "E-1"
  },
  {
    uid: 14,
    artName: "F♯",
    step: "F",
    alter: 1,
    semitone: 6,
    stepId: 3,
    fifthValue: 6,
    pianoKeyId: 6,
    isNormal: true,
    isBlack: true,
    mathName: "F+1"
  },
  {
    uid: 15,
    artName: "F♭",
    step: "F",
    alter: -1,
    semitone: 4,
    stepId: 3,
    fifthValue: -8,
    pianoKeyId: 4,
    isNormal: false,
    isBlack: false,
    mathName: "F-1"
  },
  {
    uid: 16,
    artName: "G♯",
    step: "G",
    alter: 1,
    semitone: 8,
    stepId: 4,
    fifthValue: 8,
    pianoKeyId: 8,
    isNormal: true,
    isBlack: true,
    mathName: "G+1"
  },
  {
    uid: 17,
    artName: "G♭",
    step: "G",
    alter: -1,
    semitone: 6,
    stepId: 4,
    fifthValue: -6,
    pianoKeyId: 6,
    isNormal: true,
    isBlack: true,
    mathName: "G-1"
  },
  {
    uid: 18,
    artName: "A♯",
    step: "A",
    alter: 1,
    semitone: 10,
    stepId: 5,
    fifthValue: 10,
    pianoKeyId: 10,
    isNormal: true,
    isBlack: true,
    mathName: "A+1"
  },
  {
    uid: 19,
    artName: "A♭",
    step: "A",
    alter: -1,
    semitone: 8,
    stepId: 5,
    fifthValue: -4,
    pianoKeyId: 8,
    isNormal: true,
    isBlack: true,
    mathName: "A-1"
  },
  {
    uid: 20,
    artName: "B♯",
    step: "B",
    alter: 1,
    semitone: 12,
    stepId: 6,
    fifthValue: 12,
    pianoKeyId: 0,
    isNormal: false,
    isBlack: false,
    mathName: "B+1"
  },
  {
    uid: 21,
    artName: "B♭",
    step: "B",
    alter: -1,
    semitone: 10,
    stepId: 6,
    fifthValue: -2,
    pianoKeyId: 10,
    isNormal: true,
    isBlack: true,
    mathName: "B-1"
  },
  {
    uid: 22,
    artName: "C♯♯",
    step: "C",
    alter: 2,
    semitone: 2,
    stepId: 0,
    fifthValue: 14,
    pianoKeyId: 2,
    isNormal: false,
    isBlack: false,
    mathName: "C+2"
  },
  {
    uid: 23,
    artName: "C♭♭",
    step: "C",
    alter: -2,
    semitone: -2,
    stepId: 0,
    fifthValue: -14,
    pianoKeyId: 10,
    isNormal: false,
    isBlack: true,
    mathName: "C-2"
  },
  {
    uid: 24,
    artName: "D♯♯",
    step: "D",
    alter: 2,
    semitone: 4,
    stepId: 1,
    fifthValue: 16,
    pianoKeyId: 4,
    isNormal: false,
    isBlack: false,
    mathName: "D+2"
  },
  {
    uid: 25,
    artName: "D♭♭",
    step: "D",
    alter: -2,
    semitone: 0,
    stepId: 1,
    fifthValue: -12,
    pianoKeyId: 0,
    isNormal: false,
    isBlack: false,
    mathName: "D-2"
  },
  {
    uid: 26,
    artName: "E♯♯",
    step: "E",
    alter: 2,
    semitone: 6,
    stepId: 2,
    fifthValue: 18,
    pianoKeyId: 6,
    isNormal: false,
    isBlack: true,
    mathName: "E+2"
  },
  {
    uid: 27,
    artName: "E♭♭",
    step: "E",
    alter: -2,
    semitone: 2,
    stepId: 2,
    fifthValue: -10,
    pianoKeyId: 2,
    isNormal: false,
    isBlack: false,
    mathName: "E-2"
  },
  {
    uid: 28,
    artName: "F♯♯",
    step: "F",
    alter: 2,
    semitone: 7,
    stepId: 3,
    fifthValue: 13,
    pianoKeyId: 7,
    isNormal: false,
    isBlack: false,
    mathName: "F+2"
  },
  {
    uid: 29,
    artName: "F♭♭",
    step: "F",
    alter: -2,
    semitone: 3,
    stepId: 3,
    fifthValue: -15,
    pianoKeyId: 3,
    isNormal: false,
    isBlack: true,
    mathName: "F-2"
  },
  {
    uid: 30,
    artName: "G♯♯",
    step: "G",
    alter: 2,
    semitone: 9,
    stepId: 4,
    fifthValue: 15,
    pianoKeyId: 9,
    isNormal: false,
    isBlack: false,
    mathName: "G+2"
  },
  {
    uid: 31,
    artName: "G♭♭",
    step: "G",
    alter: -2,
    semitone: 5,
    stepId: 4,
    fifthValue: -13,
    pianoKeyId: 5,
    isNormal: false,
    isBlack: false,
    mathName: "G-2"
  },
  {
    uid: 32,
    artName: "A♯♯",
    step: "A",
    alter: 2,
    semitone: 11,
    stepId: 5,
    fifthValue: 17,
    pianoKeyId: 11,
    isNormal: false,
    isBlack: false,
    mathName: "A+2"
  },
  {
    uid: 33,
    artName: "A♭♭",
    step: "A",
    alter: -2,
    semitone: 7,
    stepId: 5,
    fifthValue: -11,
    pianoKeyId: 7,
    isNormal: false,
    isBlack: false,
    mathName: "A-2"
  },
  {
    uid: 34,
    artName: "B♯♯",
    step: "B",
    alter: 2,
    semitone: 13,
    stepId: 6,
    fifthValue: 19,
    pianoKeyId: 1,
    isNormal: false,
    isBlack: true,
    mathName: "B+2"
  },
  {
    uid: 35,
    artName: "B♭♭",
    step: "B",
    alter: -2,
    semitone: 9,
    stepId: 6,
    fifthValue: -9,
    pianoKeyId: 9,
    isNormal: false,
    isBlack: false,
    mathName: "B-2"
  }
])

export default noteMeta
