import collect from 'collect.js';

export default collect(
  [
    {
      uid: 1,
      artName: "C",
      step: "C",
      alter: 0,
      semitone: 0,
      stepIndex: 0,
      fifthValue: 0,
      locationId: 0,
      isNormal: true,
      isBlack: false,
      mathName: "C"
    },
    {
      uid: 2,
      artName: "D",
      step: "D",
      alter: 0,
      semitone: 2,
      stepIndex: 1,
      fifthValue: 2,
      locationId: 2,
      isNormal: true,
      isBlack: false,
      mathName: "D"
    },
    {
      uid: 3,
      artName: "E",
      step: "E",
      alter: 0,
      semitone: 4,
      stepIndex: 2,
      fifthValue: 4,
      locationId: 4,
      isNormal: true,
      isBlack: false,
      mathName: "E"
    },
    {
      uid: 4,
      artName: "F",
      step: "F",
      alter: 0,
      semitone: 5,
      stepIndex: 3,
      fifthValue: -1,
      locationId: 5,
      isNormal: true,
      isBlack: false,
      mathName: "F"
    },
    {
      uid: 5,
      artName: "G",
      step: "G",
      alter: 0,
      semitone: 7,
      stepIndex: 4,
      fifthValue: 1,
      locationId: 7,
      isNormal: true,
      isBlack: false,
      mathName: "G"
    },
    {
      uid: 6,
      artName: "A",
      step: "A",
      alter: 0,
      semitone: 9,
      stepIndex: 5,
      fifthValue: 3,
      locationId: 9,
      isNormal: true,
      isBlack: false,
      mathName: "A"
    },
    {
      uid: 7,
      artName: "B",
      step: "B",
      alter: 0,
      semitone: 11,
      stepIndex: 6,
      fifthValue: 5,
      locationId: 11,
      isNormal: true,
      isBlack: false,
      mathName: "B"
    },
    {
      uid: 8,
      artName: "C♯",
      step: "C",
      alter: 1,
      semitone: 1,
      stepIndex: 0,
      fifthValue: 7,
      locationId: 1,
      isNormal: true,
      isBlack: true,
      mathName: "C+1"
    },
    {
      uid: 9,
      artName: "C♭",
      step: "C",
      alter: -1,
      semitone: -1,
      stepIndex: 0,
      fifthValue: -7,
      locationId: 11,
      isNormal: false,
      isBlack: false,
      mathName: "C-1"
    },
    {
      uid: 10,
      artName: "D♯",
      step: "D",
      alter: 1,
      semitone: 3,
      stepIndex: 1,
      fifthValue: 9,
      locationId: 3,
      isNormal: true,
      isBlack: true,
      mathName: "D+1"
    },
    {
      uid: 11,
      artName: "D♭",
      step: "D",
      alter: -1,
      semitone: 1,
      stepIndex: 1,
      fifthValue: -5,
      locationId: 1,
      isNormal: true,
      isBlack: true,
      mathName: "D-1"
    },
    {
      uid: 12,
      artName: "E♯",
      step: "E",
      alter: 1,
      semitone: 5,
      stepIndex: 2,
      fifthValue: 11,
      locationId: 5,
      isNormal: false,
      isBlack: false,
      mathName: "E+1"
    },
    {
      uid: 13,
      artName: "E♭",
      step: "E",
      alter: -1,
      semitone: 3,
      stepIndex: 2,
      fifthValue: -3,
      locationId: 3,
      isNormal: true,
      isBlack: true,
      mathName: "E-1"
    },
    {
      uid: 14,
      artName: "F♯",
      step: "F",
      alter: 1,
      semitone: 6,
      stepIndex: 3,
      fifthValue: 6,
      locationId: 6,
      isNormal: true,
      isBlack: true,
      mathName: "F+1"
    },
    {
      uid: 15,
      artName: "F♭",
      step: "F",
      alter: -1,
      semitone: 4,
      stepIndex: 3,
      fifthValue: -8,
      locationId: 4,
      isNormal: false,
      isBlack: false,
      mathName: "F-1"
    },
    {
      uid: 16,
      artName: "G♯",
      step: "G",
      alter: 1,
      semitone: 8,
      stepIndex: 4,
      fifthValue: 8,
      locationId: 8,
      isNormal: true,
      isBlack: true,
      mathName: "G+1"
    },
    {
      uid: 17,
      artName: "G♭",
      step: "G",
      alter: -1,
      semitone: 6,
      stepIndex: 4,
      fifthValue: -6,
      locationId: 6,
      isNormal: true,
      isBlack: true,
      mathName: "G-1"
    },
    {
      uid: 18,
      artName: "A♯",
      step: "A",
      alter: 1,
      semitone: 10,
      stepIndex: 5,
      fifthValue: 10,
      locationId: 10,
      isNormal: true,
      isBlack: true,
      mathName: "A+1"
    },
    {
      uid: 19,
      artName: "A♭",
      step: "A",
      alter: -1,
      semitone: 8,
      stepIndex: 5,
      fifthValue: -4,
      locationId: 8,
      isNormal: true,
      isBlack: true,
      mathName: "A-1"
    },
    {
      uid: 20,
      artName: "B♯",
      step: "B",
      alter: 1,
      semitone: 12,
      stepIndex: 6,
      fifthValue: 12,
      locationId: 0,
      isNormal: false,
      isBlack: false,
      mathName: "B+1"
    },
    {
      uid: 21,
      artName: "B♭",
      step: "B",
      alter: -1,
      semitone: 10,
      stepIndex: 6,
      fifthValue: -2,
      locationId: 10,
      isNormal: true,
      isBlack: true,
      mathName: "B-1"
    },
    {
      uid: 22,
      artName: "C♯♯",
      step: "C",
      alter: 2,
      semitone: 2,
      stepIndex: 0,
      fifthValue: 14,
      locationId: 2,
      isNormal: false,
      isBlack: false,
      mathName: "C+2"
    },
    {
      uid: 23,
      artName: "C♭♭",
      step: "C",
      alter: -2,
      semitone: -2,
      stepIndex: 0,
      fifthValue: -14,
      locationId: 10,
      isNormal: false,
      isBlack: true,
      mathName: "C-2"
    },
    {
      uid: 24,
      artName: "D♯♯",
      step: "D",
      alter: 2,
      semitone: 4,
      stepIndex: 1,
      fifthValue: 16,
      locationId: 4,
      isNormal: false,
      isBlack: false,
      mathName: "D+2"
    },
    {
      uid: 25,
      artName: "D♭♭",
      step: "D",
      alter: -2,
      semitone: 0,
      stepIndex: 1,
      fifthValue: -12,
      locationId: 0,
      isNormal: false,
      isBlack: false,
      mathName: "D-2"
    },
    {
      uid: 26,
      artName: "E♯♯",
      step: "E",
      alter: 2,
      semitone: 6,
      stepIndex: 2,
      fifthValue: 18,
      locationId: 6,
      isNormal: false,
      isBlack: true,
      mathName: "E+2"
    },
    {
      uid: 27,
      artName: "E♭♭",
      step: "E",
      alter: -2,
      semitone: 2,
      stepIndex: 2,
      fifthValue: -10,
      locationId: 2,
      isNormal: false,
      isBlack: false,
      mathName: "E-2"
    },
    {
      uid: 28,
      artName: "F♯♯",
      step: "F",
      alter: 2,
      semitone: 7,
      stepIndex: 3,
      fifthValue: 13,
      locationId: 7,
      isNormal: false,
      isBlack: false,
      mathName: "F+2"
    },
    {
      uid: 29,
      artName: "F♭♭",
      step: "F",
      alter: -2,
      semitone: 3,
      stepIndex: 3,
      fifthValue: -15,
      locationId: 3,
      isNormal: false,
      isBlack: true,
      mathName: "F-2"
    },
    {
      uid: 30,
      artName: "G♯♯",
      step: "G",
      alter: 2,
      semitone: 9,
      stepIndex: 4,
      fifthValue: 15,
      locationId: 9,
      isNormal: false,
      isBlack: false,
      mathName: "G+2"
    },
    {
      uid: 31,
      artName: "G♭♭",
      step: "G",
      alter: -2,
      semitone: 5,
      stepIndex: 4,
      fifthValue: -13,
      locationId: 5,
      isNormal: false,
      isBlack: false,
      mathName: "G-2"
    },
    {
      uid: 32,
      artName: "A♯♯",
      step: "A",
      alter: 2,
      semitone: 11,
      stepIndex: 5,
      fifthValue: 17,
      locationId: 11,
      isNormal: false,
      isBlack: false,
      mathName: "A+2"
    },
    {
      uid: 33,
      artName: "A♭♭",
      step: "A",
      alter: -2,
      semitone: 7,
      stepIndex: 5,
      fifthValue: -11,
      locationId: 7,
      isNormal: false,
      isBlack: false,
      mathName: "A-2"
    },
    {
      uid: 34,
      artName: "B♯♯",
      step: "B",
      alter: 2,
      semitone: 13,
      stepIndex: 6,
      fifthValue: 19,
      locationId: 1,
      isNormal: false,
      isBlack: true,
      mathName: "B+2"
    },
    {
      uid: 35,
      artName: "B♭♭",
      step: "B",
      alter: -2,
      semitone: 9,
      stepIndex: 6,
      fifthValue: -9,
      locationId: 9,
      isNormal: false,
      isBlack: false,
      mathName: "B-2"
    }
  ]
)