import collect from "collect.js";

export default collect(
  [
    {
      rawNoteStep: "C",
      rawNoteAlter: -1,
      mode: "major",
      actualNoteStep: "B",
      actualNoteAlter: 0,
      isTonicReplaced: true,
      isTonicNormal: false,
      isDoubleAlterIncluded: false,
      rawStaveAlters: -7,
      circleID: 5
    },
    {
      rawNoteStep: "C",
      rawNoteAlter: 0,
      mode: "major",
      actualNoteStep: "C",
      actualNoteAlter: 0,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: 0,
      circleID: 0
    },
    {
      rawNoteStep: "C",
      rawNoteAlter: 1,
      mode: "major",
      actualNoteStep: "D",
      actualNoteAlter: -1,
      isTonicReplaced: true,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: 7,
      circleID: 7
    },
    {
      rawNoteStep: "D",
      rawNoteAlter: -1,
      mode: "major",
      actualNoteStep: "D",
      actualNoteAlter: -1,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: -5,
      circleID: 7
    },
    {
      rawNoteStep: "D",
      rawNoteAlter: 0,
      mode: "major",
      actualNoteStep: "D",
      actualNoteAlter: 0,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: 2,
      circleID: 2
    },
    {
      rawNoteStep: "D",
      rawNoteAlter: 1,
      mode: "major",
      actualNoteStep: "E",
      actualNoteAlter: -1,
      isTonicReplaced: true,
      isTonicNormal: true,
      isDoubleAlterIncluded: true,
      rawStaveAlters: 9,
      circleID: -1
    },
    {
      rawNoteStep: "E",
      rawNoteAlter: -1,
      mode: "major",
      actualNoteStep: "E",
      actualNoteAlter: -1,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: -3,
      circleID: 9
    },
    {
      rawNoteStep: "E",
      rawNoteAlter: 0,
      mode: "major",
      actualNoteStep: "E",
      actualNoteAlter: 0,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: 4,
      circleID: 4
    },
    {
      rawNoteStep: "E",
      rawNoteAlter: 1,
      mode: "major",
      actualNoteStep: "F",
      actualNoteAlter: 0,
      isTonicReplaced: true,
      isTonicNormal: false,
      isDoubleAlterIncluded: true,
      rawStaveAlters: 11,
      circleID: -1
    },
    {
      rawNoteStep: "F",
      rawNoteAlter: -1,
      mode: "major",
      actualNoteStep: "E",
      actualNoteAlter: 0,
      isTonicReplaced: true,
      isTonicNormal: false,
      isDoubleAlterIncluded: true,
      rawStaveAlters: -8,
      circleID: -1
    },
    {
      rawNoteStep: "F",
      rawNoteAlter: 0,
      mode: "major",
      actualNoteStep: "F",
      actualNoteAlter: 0,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: -1,
      circleID: 11
    },
    {
      rawNoteStep: "F",
      rawNoteAlter: 1,
      mode: "major",
      actualNoteStep: "F",
      actualNoteAlter: 1,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: 6,
      circleID: 6
    },
    {
      rawNoteStep: "G",
      rawNoteAlter: -1,
      mode: "major",
      actualNoteStep: "G",
      actualNoteAlter: -1,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: -6,
      circleID: 6
    },
    {
      rawNoteStep: "G",
      rawNoteAlter: 0,
      mode: "major",
      actualNoteStep: "G",
      actualNoteAlter: 0,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: 1,
      circleID: 1
    },
    {
      rawNoteStep: "G",
      rawNoteAlter: 1,
      mode: "major",
      actualNoteStep: "A",
      actualNoteAlter: -1,
      isTonicReplaced: true,
      isTonicNormal: true,
      isDoubleAlterIncluded: true,
      rawStaveAlters: 8,
      circleID: -1
    },
    {
      rawNoteStep: "A",
      rawNoteAlter: -1,
      mode: "major",
      actualNoteStep: "A",
      actualNoteAlter: -1,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: -4,
      circleID: 8
    },
    {
      rawNoteStep: "A",
      rawNoteAlter: 0,
      mode: "major",
      actualNoteStep: "A",
      actualNoteAlter: 0,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: 3,
      circleID: 3
    },
    {
      rawNoteStep: "A",
      rawNoteAlter: 1,
      mode: "major",
      actualNoteStep: "B",
      actualNoteAlter: -1,
      isTonicReplaced: true,
      isTonicNormal: true,
      isDoubleAlterIncluded: true,
      rawStaveAlters: 10,
      circleID: -1
    },
    {
      rawNoteStep: "B",
      rawNoteAlter: -1,
      mode: "major",
      actualNoteStep: "B",
      actualNoteAlter: -1,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: -2,
      circleID: 10
    },
    {
      rawNoteStep: "B",
      rawNoteAlter: 0,
      mode: "major",
      actualNoteStep: "B",
      actualNoteAlter: 0,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: 5,
      circleID: 5
    },
    {
      rawNoteStep: "B",
      rawNoteAlter: 1,
      mode: "major",
      actualNoteStep: "C",
      actualNoteAlter: 0,
      isTonicReplaced: true,
      isTonicNormal: false,
      isDoubleAlterIncluded: true,
      rawStaveAlters: 12,
      circleID: -1
    },
    {
      rawNoteStep: "C",
      rawNoteAlter: -1,
      mode: "minor",
      actualNoteStep: "B",
      actualNoteAlter: 0,
      isTonicReplaced: true,
      isTonicNormal: false,
      isDoubleAlterIncluded: true,
      rawStaveAlters: -10,
      circleID: -1
    },
    {
      rawNoteStep: "C",
      rawNoteAlter: 0,
      mode: "minor",
      actualNoteStep: "C",
      actualNoteAlter: 0,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: -3,
      circleID: 9
    },
    {
      rawNoteStep: "C",
      rawNoteAlter: 1,
      mode: "minor",
      actualNoteStep: "C",
      actualNoteAlter: 1,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: 4,
      circleID: 4
    },
    {
      rawNoteStep: "D",
      rawNoteAlter: -1,
      mode: "minor",
      actualNoteStep: "C",
      actualNoteAlter: 1,
      isTonicReplaced: true,
      isTonicNormal: true,
      isDoubleAlterIncluded: true,
      rawStaveAlters: -8,
      circleID: -1
    },
    {
      rawNoteStep: "D",
      rawNoteAlter: 0,
      mode: "minor",
      actualNoteStep: "D",
      actualNoteAlter: 0,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: -1,
      circleID: 11
    },
    {
      rawNoteStep: "D",
      rawNoteAlter: 1,
      mode: "minor",
      actualNoteStep: "D",
      actualNoteAlter: 1,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: 6,
      circleID: 6
    },
    {
      rawNoteStep: "E",
      rawNoteAlter: -1,
      mode: "minor",
      actualNoteStep: "E",
      actualNoteAlter: -1,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: -6,
      circleID: 6
    },
    {
      rawNoteStep: "E",
      rawNoteAlter: 0,
      mode: "minor",
      actualNoteStep: "E",
      actualNoteAlter: 0,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: 1,
      circleID: 1
    },
    {
      rawNoteStep: "E",
      rawNoteAlter: 1,
      mode: "minor",
      actualNoteStep: "F",
      actualNoteAlter: 0,
      isTonicReplaced: true,
      isTonicNormal: false,
      isDoubleAlterIncluded: true,
      rawStaveAlters: 8,
      circleID: -1
    },
    {
      rawNoteStep: "F",
      rawNoteAlter: -1,
      mode: "minor",
      actualNoteStep: "E",
      actualNoteAlter: 0,
      isTonicReplaced: true,
      isTonicNormal: false,
      isDoubleAlterIncluded: true,
      rawStaveAlters: -11,
      circleID: -1
    },
    {
      rawNoteStep: "F",
      rawNoteAlter: 0,
      mode: "minor",
      actualNoteStep: "F",
      actualNoteAlter: 0,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: -4,
      circleID: 8
    },
    {
      rawNoteStep: "F",
      rawNoteAlter: 1,
      mode: "minor",
      actualNoteStep: "F",
      actualNoteAlter: 1,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: 3,
      circleID: 3
    },
    {
      rawNoteStep: "G",
      rawNoteAlter: -1,
      mode: "minor",
      actualNoteStep: "F",
      actualNoteAlter: 1,
      isTonicReplaced: true,
      isTonicNormal: true,
      isDoubleAlterIncluded: true,
      rawStaveAlters: -9,
      circleID: -1
    },
    {
      rawNoteStep: "G",
      rawNoteAlter: 0,
      mode: "minor",
      actualNoteStep: "G",
      actualNoteAlter: 0,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: -2,
      circleID: 10
    },
    {
      rawNoteStep: "G",
      rawNoteAlter: 1,
      mode: "minor",
      actualNoteStep: "G",
      actualNoteAlter: 1,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: 5,
      circleID: 5
    },
    {
      rawNoteStep: "A",
      rawNoteAlter: -1,
      mode: "minor",
      actualNoteStep: "G",
      actualNoteAlter: 1,
      isTonicReplaced: true,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: -7,
      circleID: 5
    },
    {
      rawNoteStep: "A",
      rawNoteAlter: 0,
      mode: "minor",
      actualNoteStep: "A",
      actualNoteAlter: 0,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: 0,
      circleID: 0
    },
    {
      rawNoteStep: "A",
      rawNoteAlter: 1,
      mode: "minor",
      actualNoteStep: "B",
      actualNoteAlter: -1,
      isTonicReplaced: true,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: 7,
      circleID: 7
    },
    {
      rawNoteStep: "B",
      rawNoteAlter: -1,
      mode: "minor",
      actualNoteStep: "B",
      actualNoteAlter: -1,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: -5,
      circleID: 7
    },
    {
      rawNoteStep: "B",
      rawNoteAlter: 0,
      mode: "minor",
      actualNoteStep: "B",
      actualNoteAlter: 0,
      isTonicReplaced: false,
      isTonicNormal: true,
      isDoubleAlterIncluded: false,
      rawStaveAlters: 2,
      circleID: 2
    },
    {
      rawNoteStep: "B",
      rawNoteAlter: 1,
      mode: "minor",
      actualNoteStep: "C",
      actualNoteAlter: 0,
      isTonicReplaced: true,
      isTonicNormal: false,
      isDoubleAlterIncluded: true,
      rawStaveAlters: 9,
      circleID: -1
    }
  ]
)
